- .gdbinit
- build/i386-pc/make/makefile
- build/or1k-pc/make/makefile
- src/test/build/makefile.i386-pc
- src/test/build/makefile.or1k-pc
- tools/run/run-qemu.sh
**Description**
In this pull request I have fixed the building system for the x86-qemu and openrisc-qemu targets.
We were using out of date scripts.
> Bug Fix: Out of Date Run Script

- build/or1k-pc/linker/link.ld
Previously we were wrong referring to objects in the link script. As a
consequence, the interrupt vector of the or1k-pc target would be messed
up in some systems causing interrupts to misbehavior.
> [or1k-qemu] Bug Fix: Bad Link Script

- build/or1k-pc/linker/link.ld
- include/arch/core/or1k/clock.h
- src/hal/arch/core/or1k/clock.c
Previously, we were using a bad frequency for the clock. In this commit,
we fixed this problem.
> [or1k-core] Bug Fix: Bad Clock Frequency

- include/arch/core/k1b/asm.h
- include/nanvix/klib.h
- src/hal/arch/core/k1b/ivt.c
- src/test/main.c
Description
Currently, when registering exception stacks at startup, we are using base addresses instead of their base ones. As consequence, the exception handler dispatcher is potentially trashing the memory, thereby leading to complete chaos. In this commit, I have fixed this problem.
Related Issues
- [[k1b] Bad Exception Stack Configuration](https://github.com/nanvix/hal/issues/88)
>  [k1b-core] Bad Exception Stack

- include/arch/core/k1b/asm.h
- include/arch/core/k1b/context.h
- include/arch/core/k1b/excp.h
- include/nanvix/klib.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/ivt.c
- src/test/arch/k1b.S
- src/test/build/makefile.i386-pc
- src/test/build/makefile.mppa256
- src/test/build/makefile.or1k-pc
- src/test/exception.c
- src/test/main.c
- src/test/makefile
- src/test/test.h
Description
When an exception is raised in any core of an IO Cluster, it triggers multiple faults and causes execution flow to loop indefinitely.
An initial investigation suggests that as soon as space is allocated in the kernel stack to save the interrupted execution context and the first value is pushed, the first nestes fault is launched.
Related Issues
- [[k1bio] Exceptions Trigger Multiple Faults](https://github.com/nanvix/hal/issues/89)
> [k1b-core] Exceptions Trigger Multiple Faults

- include/arch/core/or1k/excp.h
- src/hal/arch/core/or1k/hooks.S
Description
Previously, the exception structure of the or1k core was 12-bytes long, although the Exception Interface requires this structure to be a multiple of a double word. In this commit, I fixed this problem by padding the exception structure so as it has 16 bytes.
Related Issues
- [[or1k-core] Bad Exception Strucure Padding](https://github.com/nanvix/hal/issues/106)
> [or1k-core] Bug Fix: Bad Exception Struct Padding

- src/hal/arch/core/or1k/core.c
Description
In the current implementation of the Core Interface for or1k cores, we are locking twice the same entry of the cores table, when calling or1k_core_idle() from or1k_core_reset(). Since spinlocks are not re-entrant, we end up freezing the core.
Related Issues
- [[or1k-core] Locking Same Entry of Cores Table Twice](https://github.com/nanvix/hal/issues/124)
> [or1k-core] Locking Same Entry of Cores Table 2x

- include/arch/core/k1b/pic.h
Description
Previously, we were doing the opposite of what we were supposed to do
concerning interrupt masking. When we were supposed to unmask an
interrupt, we were masking it and vice-versa. In this commit, I fix this
bug.
Related Issues
- [[k1b-core] Bad Interrupt Masking](https://github.com/nanvix/hal/issues/144)
> [k1b-core] Bad Interrupt Masking

- include/arch/core/or1k/pic.h
- src/test/clock.c
Description
Previously, we were assuming that all interrupt masks were cleared, so
that if we simply enabled hardware interrupts clock interrupts would
follow. However, enabling hardware interrupts and unmasking them are two
different things that we were missing to do. In this commit, I ensure
that we unmask the clock interrupt line before proceeding with tests.
> [hal] Unmask Clock Interrupt

- include/nanvix/klib.h
Description
Previously, we were using a very small kernel buffer size that would sometimes overflow and cause the HAL to misbehave. In this commit, I have fixed this problem by making the buffer size 2x bigger.
> [hal][lib] Buffer Size Too Small

- include/arch/core/i486/8259.h
- include/arch/core/i486/int.h
- include/arch/core/k1b/int.h
- include/arch/core/k1b/pic.h
- include/arch/core/or1k/int.h
- include/arch/core/or1k/pic.h
- include/nanvix/hal/core/interrupt.h
- src/hal/arch/core/i486/8259.c
- src/hal/arch/core/i486/clock.c
- src/hal/arch/core/i486/hwint.c
- src/hal/arch/core/k1b/hwint.c
- src/hal/arch/core/or1k/hwint.c
- src/hal/core/interrupt.c
Description
In this PR, I introduce several enhancements in the Hardware Interrupt Interface:
- Adding a return value for `interrupt_set_handler()`
- Adding `interrupt_unregister()` routine
- Adding parameter checking
- Using the standard output format for messages
Related Issues
- [[hal] Hardware Interrupt Interface](https://github.com/nanvix/hal/issues/8)
> [hal] Enhancements in the Hardware Interrupt Interface

- include/arch/core/i486/excp.h
- include/arch/core/k1b/excp.h
- include/arch/core/or1k/excp.h
- include/nanvix/hal/core/exception.h
- src/hal/arch/core/i486/excp.c
- src/hal/arch/core/k1b/excp.c
- src/hal/arch/core/or1k/excp.c
Description
In this PR, I introduce several enhancements in the Hardware Interrupt Interface:
- Adding a return value for `exception_set_handler()`
- Adding `exception_unset_handler()` routine
- Adding parameter checking
Related Issues
- [[hal] Exception Interface](https://github.com/nanvix/hal/issues/9)
> [hal] Enhancements in the Exception Interface

- tools/dev/setup-qemu.sh
In this commit, I have removed the or1k-linux-user QEMU target. We do
not use it.
> Enhancement: Drop Some Useless QEMU Targets

- tools/dev/arch/or1k.sh
We don't need the GCC for Linux. In this commit I have dropped this from
the toolchain build.
> [build] Cleanup OpenRISC Toolchain

- src/hal/arch/core/or1k/hooks.S
Since the syscall arguments have changed in HAL, the or1k-core were using an outdated interface for system calls, thus, this PR solves #128.
> [or1k-core] Bug Fix: Outdated Number of Syscalls Arguments

- include/arch/core/or1k/asm.h
- src/hal/arch/core/or1k/_core.S
- src/hal/arch/core/or1k/hooks.S
In issue #143 was observed that `_or1k_core_reset` was literally doing nothing. This is reminiscent of the much earlier stages of the HAL port to or1k. Since the port is in advanced stage, it is essential to implement this function.
> [or1k-core] Properly Resetting Core

- include/arch/core/or1k/asm.h
Description
This PR introduces the macros suggested in #154.
Since OpenRISC 32-bit does not makes use of 64-bit registers and structures, does not makes sense at all to use the pseudo-instructions `pushd` and `popd` so they will not be implemented.
@ppenna Just a side note: this pull request also contains the changes included in PR #166, so please review the previous PR before this one.
Related Issues
- [[or1k-core] ASM Macros](https://github.com/nanvix/hal/issues/154)
> [or1k-core] Enhancement: ASM Macros

- src/hal/arch/core/k1b/hooks.S
Description
Previously, we were missing to save all preserved registers in a trap call. In this commit, I fix this bug. Note that we were not getting some error before because mOS issues a memory barrier before issue a system call. However, it is not safe to assume this behavior.
> [k1b-core] Save Preserved Regs in Trap

- src/hal/arch/core/k1b/hooks.S
Description
mOS supports trap calls with 8 arguments, and thus the trap call number is stored in the R7.  However, we support trap calls only with 5 arguments, but we were missing to use R5 register to store the trap call number, previously. In this commit, I fix this bug.
- [[k1b-core] Save Preserved Regs in Trap](https://github.com/nanvix/hal/pull/168)
> [k1b-core] Bad Trap Call Arguments

- include/arch/core/k1b/tlb.h
- include/arch/core/or1k/tlb.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/tlb.h
- include/nanvix/hal/core/trap.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/tlb.c
- src/hal/arch/core/or1k/hooks.S
- src/hal/arch/core/or1k/mmu.c
- src/hal/arch/core/or1k/tlb.c
- src/test/syscalls.c
Description
Previously, whenever looking up an TLB entry, either by a physical or virtual address, we would return an TLB entry even if it was an invalid one. In this commit, I fix this bug.
- [[hal] Casts for Virtual and Physical Address](https://github.com/nanvix/hal/pull/172)
> [k1b-core] Bad TLB Lookups

- src/hal/arch/core/k1b/tlb.c
Description
Previously, we would thrash the contents of the in-memory TLB if we had some problem when saving/invalidating the target hardware TLB entry. In this commit, I fix this bug.
> [k1b-core]  Dont Trash In-Memory TLB

- src/hal/arch/core/or1k/tlb.c
In issue #176, we are getting page fault due to wrong permissions on the `or1k_tlb_write` function. This behavior occurred because the `kcode` variable was wrong during the comparison and thus erroneously identified the address as kernel code rather than user.
To force the correct behavior, I've used the `volatile` keyword, so we can ensure that the value is on the stack and is retrieved correctly, without being used elsewhere and getting dirty.
> [or1k-core] Bug Fix: Wrong Permissions in TLB Entry

- include/arch/core/or1k/tlb.h
In order to the fault injection tests pass (#181) we need to ensure that the TLB type is one of the allowed.
> [or1k-core] Bug Fix: Checking TLB Types

- include/arch/cluster/i486.h
- include/arch/cluster/k1b.h
- include/arch/cluster/or1k.h
- include/arch/cluster/or1k/memory.h
- include/arch/core/i486/mmu.h
- include/arch/core/k1b/mmu.h
- include/arch/core/or1k/mmu.h
- include/arch/core/rv32i.h
- include/arch/core/rv32i/mmu.h
- include/nanvix/hal/cluster/mmio.h
- include/nanvix/hal/core/mmu.h
- src/hal/core/mmu.c
- src/hal/stdout/8250.c
Description
Although this PR is intended to cover the MMIO interface in OpenRISC, it also changes the HAL MMIO interface, since my last talk to @ppenna, this simplified version requires a minimal change in the other targets and it's generic enough to fit in the HAL.
Note: it's up to the other targets to implement the required function `mmu_is_enabled()`, which justifies the Travis CI building errors (for x86 and riscv)..
Related Issues
[[hal] Simpler MMIO Interface](https://github.com/nanvix/hal/issues/236)
[[hal] Page Walk](https://github.com/nanvix/hal/issues/237)
[[openrisc-qemu] Freezing While Trying to Write into Serial Device](https://github.com/nanvix/hal/issues/116)
> [openrisc] Feature: OpenRISC MMIO

- src/hal/core/interrupt.c
Description
Previously, after registering/unregistering an interrupt handler for a given interrupt, the interrupt would need to be masked/unmasked by explicitly calling either `interrupt_mask()` or `interrupt_unmask()`. In this commit, I make things more natural: the interrupt is automatically masked/unmasked when a handler is registered/unregistered for it.
Related Issues
- [[hal] Auto Mask/Unmask Interrupts](https://github.com/nanvix/hal/issues/235)
> [hal] Auto Mask/Unmask Interrupts

- include/nanvix/hal/core/interrupt.h
- src/hal/core/interrupt.c
Description
A lot of spurious interrupts may suggest that the software is buggy. In this commit, I introduce a simple mechanism that keeps track of the number of spurious interrupts that were are getting and, if this number grows to much we pedantically output warning messages.
Related Issues
- [[hal] Keep Track of Spurious Interrupts](https://github.com/nanvix/hal/issues/238)
- [[hal] Auto Mask/Unmask Interrupts](https://github.com/nanvix/hal/pull/239)
> [hal] Track Spurious Interrupts

- include/arch/core/i486/8253.h
- include/arch/core/k1b/clock.h
- include/arch/core/mor1kx/clock.h
- include/arch/core/or1k/clock.h
- include/nanvix/hal/core/clock.h
- include/nanvix/hal/core/interrupt.h
- src/hal/arch/core/or1k/clock.c
- src/hal/arch/core/or1k/hwint.c
- src/hal/core/interrupt.c
Description
In some architectures, such as OpenRISC, the counter of the integrated clock device should be explicitly reset at each clock interrupt, so that a next interrupt will follow.
In this Pull Request, I introduce the `clock_reset()` operation to the Clock Interface.
Related Issues
- [[hal] Clock Timer Reset](https://github.com/nanvix/hal/issues/241)
- [[hal] Auto Mask/Unmask Interrupts](https://github.com/nanvix/hal/pull/239)
- [[hal] Track Spurious Interrupts](https://github.com/nanvix/hal/pull/240)
> [hal] Clock Timer Reset

- src/test/core.c
Description
In the unit test introduced in a870ec1, the test makes use of all slave cores available. However, this test is primarily intended for test only one core to make sure if the communication between master and slave works. Tests that makes use of multiple cores will be introduced later.
Related Issues
- [[hal][test] Unit Tests for Core Interface](https://github.com/nanvix/hal/issues/2)
> [hal] Use One Slave Core in Unit tests

- include/nanvix/const.h
Description
In this commit, I introduce the `UNREACHABLE()` kernel builtin, which signals the compiler that the code that follows is never reached, thereby enabling optimizations.
Related Issues
- [[hal][lib] C Compiler Extensions](https://github.com/nanvix/hal/issues/263)
> [hal][lib] Unreachable Kernel Builtin Function

- include/nanvix/cc.h
- include/nanvix/const.h
- include/nanvix/klib.h
Description
In this commit, I introduce a header for the following C Compiler extensions:
**Keyword Aliases**
- `inline`: inline function
- `asm`: inline assembly
- `volatile`: volatile symbol
**Function Attributes**
- `NORETURN`: casts a function with no return
- `SECTION()`: places a function in a target binary section
- `OVERRIDE`: makes a symbol overwritable
**Type Attributes**
- `ALIGN` aligns n object at a boundary
- `PACK`: packs a structure
**Builtin Functions**
- `UNREACHABLE()`: makes the code that follows unreachable
- `UNUSED()`: declares something to be unsued
- `EXPECT()`: provides hints for branch condition
- `noop()`: no operation
Related Isssues
-----------------------
- [[hal][lib] C Compiler Extensions](https://github.com/nanvix/hal/issues/263)
Pull …
> [hal][lib] C Compiler Extensions

- include/nanvix/hal/core.h
- src/hal/core/core.c
Description
Since the core table should not be used outside from the core interface, it's necessary a reliable way to check whether the core was started or not, which is indeed useful for the core tests. In order to do that, the function `core_start` was slightly changed so the current state could be returned.
Related Issues
- [[hal] Return Value for Core Start](https://github.com/nanvix/hal/issues/262)
> [hal] Return Value for Core Start

- src/hal/core/core.c
Description
The core_start() routine was allowing a core to start itself, which should not be permitted by the hal, thus, this PR checks if the caller core is different from the target core.
> [hal] Bug Fix: No One Core Should Start Itself

- src/hal/core/core.c
- src/test/core.c
Description
This PR introduces the Fault Injection test "Start Instruction Execution in the Master Core" present in the Unit Core Tests (#2).
----------------------------------------
- [[hal] Bug Fix: No One Core Should Start Itself](https://github.com/nanvix/hal/pull/291)
> [hal][test] Start Instruction Execution in the Master Core

- include/arch/cluster/x86-cluster.h
- src/test/main.c
Description
The x86-qemu target does not have multiple cores inside the cluster, thus, the Core Tests will not work in it. Due that, this PR disables the Core Tests for architectures that does not features more than one core/cluster.
Related Issues
[[qemu-x86] Disable Unit Tests for Core Interface](https://github.com/nanvix/hal/issues/293)
> [x86-qemu] Disabling Unit Tests for Core Interface

- src/hal/core/core.c
Description
--------------
The routine core_start() was not checking if the function pointer passed by parameter was valid or not, which could lead to a unexpected behavior. Thus, this PR checks if valid before to proceed.
> [hal] Checking Function Pointer Before Start

- src/test/core.c
Description
--------------
This PR introduces the Fault Injection test "Start a Bad Execution Flow" present in the Unit Core Tests (#2). This test checks if the HAL is able to catch invalid calls to the core_start() function by passing a invalid function pointer.
- [[hal] Bug Fix: Checking Function Pointer Before Start](https://github.com/nanvix/hal/pull/299)
Related Issues
------------------
> [hal][test] Start a Bad Execution Flow

- src/hal/core/core.c
Description
--------------
The routine core_start() was not checking if the parameter coreid was valid or not (out of range), which could lead to an unexpected behavior. Thus, this PR checks if valid before to proceed.
- [[hal] Bug Fix: Checking Function Pointer Before Start](https://github.com/nanvix/hal/pull/299)
> [hal] Bug Fix: Checking Core ID Before Start

- src/test/core.c
Description
--------------
This PR introduces the Fault Injection test "Starts an Invalid Execution Flow" present in the Unit Core Tests (#2). This test checks if the HAL is able to catch invalid calls to the core_start() function by passing an invalid coreid.
- [[hal] Bug Fix: Checking Core ID Before Start](https://github.com/nanvix/hal/pull/301)
- [[hal][test] Enhancement: Start a Bad Execution Flow](https://github.com/nanvix/hal/pull/300)
Related Issues
------------------
> [hal][test] Starts an Invalid Execution Flow

- include/nanvix/hal/core.h
- src/hal/core/core.c
Description
--------------
The routine core_reset() should not permit that the master core resets. This is the only case that the function will in fact return a value, in all other cases, this function does not returns.
- [[hal] Bug Fix: Checking Core ID Before Start](https://github.com/nanvix/hal/pull/301)
> [hal] Master Core is Not Allowed to Reset

- src/test/core.c
Description
This PR introduces the Fault Injection test "Stop Instruction Execution in the Master Core" present in the Unit Core Tests (#2). This test checks if the HAL is able to refuse the master core from doing reset.
--------------------------------------
- [[hal] Bug Fix: Master Core is Not Allowed to Reset](https://github.com/nanvix/hal/pull/303)
- [[hal][test] Enhancement: Starts an Invalid Execution Flow](https://github.com/nanvix/hal/pull/302)
Related Issues
> [hal][test] Stop Instruction Execution in the Master Core

- include/arch/core/rv32i/spinlock.h
Description
Previously, upon initialization of a spinlock in rv32i cores we were missing a memory barrier. In this commit, I fix this bug.
> [rv32i] Memory Barrier of Spinlock Initialization

- include/arch/cluster/riscv32-cluster.h
- include/arch/processor/riscv32/_riscv32.h
- include/nanvix/hal/cluster/_cluster.h
Description
Previously, we were using bad import symbols for the RISC-V 32-Bit processor. In this commit, I fix this problem.
> [riscv32] Bad Import Symbols

- build/qemu-riscv32/make/makefile
Description
Previously, we were overriding LDFLAGS in the build. In this commit, I fix this problem.
> [qemu-riscv32] Overriding LDFLAGS

- include/stdint.h
Description
Previously we were missing an assembler guard for <stdint.h>. In this commit, I fix this problem.
> [hal][lib] Missing Assembler Guard for stdint

- build/qemu-riscv32/make/makefile
- src/hal/build/makefile.qemu-riscv32
Description
In this commit I fall back to the use of LibGCC for math stuff. Lib GCC for this target is safe.
> [qemu-riscv32] Use Lib GCC for Math

- include/nanvix/hal/core.h
- src/hal/core/core.c
Description
The HAL should not allows a wake up in an invalid core, which could lead to a unexpected behavior.
> [hal] Invalid Core Should Not Resume

- src/test/core.c
Description
--------------
This PR introduces the Fault Injection test "Resume Instruction Execution in an Invalid Core" present in the Unit Core Tests (#2). This test checks if the HAL is able to refuse a wake up in an invalid core.
- [[hal] Invalid Core Should Not Resume](https://github.com/nanvix/hal/pull/310)
Related Issues
> [hal][test] Resume Instruction Execution in an Invalid Core

- src/hal/core/core.c
Description
The HAL should not allows a wake up in a bad core, which could lead to a unexpected behavior.
--------------------------------------
- [[hal] Invalid Core Should Not Resume](https://github.com/nanvix/hal/pull/310)
> [hal] Bad Core Should Not Resume

- src/hal/core/core.c
- src/test/core.c
Description
--------------
This PR introduces the Fault Injection test "Resume Instruction Execution in a Bad Core" present in the Unit Core Tests (#2). This test checks if the HAL is able to refuse a wake up in a bad core.
--------------------------------------
- [[hal] Bad Core Should Not Resume](https://github.com/nanvix/hal/pull/312)
- [[hal][test] Resume Instruction Execution in an Invalid Core](https://github.com/nanvix/hal/pull/311)
Related Issues
> [hal][test] Resume Instruction Execution in a Bad Core

- include/arch/cluster/riscv32-cluster/memmap.h
- include/arch/cluster/riscv32-cluster/memory.h
- include/arch/core/rv32i/mmu.h
- include/arch/core/rv32i/types.h
- src/hal/arch/cluster/riscv32-cluster/memory.c
- src/hal/arch/cluster/riscv32-cluster/setup.c
- src/hal/arch/core/rv32i/mmu.c
- src/hal/core/core.c
Description
In this Pull Request, I the following extensions to the Memroy Interface:
- `cluster_mem_setup()`: initializes the memory interface
- `cluster_mem_info()`: prints information about virtual memory layout
- `cluster_mem_check_layout()`: asserts the layout of the memory
- `cluster_mem_check_align()`: asserts the alignment of the memory
- `cluster_mem_map()`: builds the memory layout
Additionally, I introduce huge page support for the MMU Interface:
- `pgtab_map()`: maps a page table
- `page_map()`: maps a page
- `huge_page_map()`: maps a huge page
Related Issues
- [[hal] Extensions for MMU Interface](https://github.com/nanvix/hal/issues/276)
- [[hal] Huge Page Support](https://github.com/nanvix/hal/issues/269)
- [[hal] Extensions for Memory …
> [riscv32-cluster] Extensions for Memory Interface

- include/arch/core/or1k/spinlock.h
- include/arch/core/rv32i/spinlock.h
Description
--------------
Since the OpenRISC GCC supports the builtins for locks and barriers, we should rely on it, instead of writing our version.
Related Issues
[[or1k-core] Missing Spinlock Memory Barrier](https://github.com/nanvix/hal/issues/175)
> [or1k-core] Bug Fix: Using Spinlocks Builtins

- include/arch/core/rv32i/mmu.h
- src/hal/build/makefile.qemu-riscv32
- src/test/build/makefile.qemu-riscv32
- src/test/main.c
Description
In this Pull Request, I enable unit tests for TLB and MMU Interfaces in rv32i cores.
Related Issues
- [[rv32i] Enable Unit Tests for MMU Interface](https://github.com/nanvix/hal/issues/296)
- [[rv32i] Enable Unit Tests for TLB Interface](https://github.com/nanvix/hal/issues/295)
> [rv32i] Enabling Unit Tests for TLB and MMU Interfaces

- include/arch/core/rv32i/clock.h
- include/arch/core/rv32i/mmu.h
- src/hal/arch/core/rv32i/clock.c
- src/hal/build/makefile.qemu-riscv32
- src/test/build/makefile.qemu-riscv32
- src/test/main.c
Description
Previously, we were using words in the implementation of the clock interface for rv32i cores. However, the clock in RISC-V architectures has a fixed-width of 64-bits, regardless the size of a word. In this Pull Request, I fix this problem.
-[[rv32i] Enabling Unit Tests for TLB and MMU Interfaces](https://github.com/nanvix/hal/pull/331)
> [rv32i] Clock Uses 64-Bit Precision

- include/arch/processor/optimsoc/_optimsoc.h
Description
In the commit 3f5841293b83522f9f36c9ffec6c4eb751e7212a the cluster header was changed and the _optimsoc header was not updated accordingly, thus, the OpTiMSoC target was not able to compile.
> [optimsoc] Bug Fix: Wrong Cluster Header

- include/arch/cluster/riscv32-cluster/clint.h
- include/arch/core/rv32i.h
- include/arch/core/rv32i/asm.h
- include/arch/core/rv32i/context.h
- include/arch/core/rv32i/excp.h
- include/arch/core/rv32i/int.h
- include/arch/core/rv32i/ivt.h
- include/arch/core/rv32i/machine.h
- include/arch/core/rv32i/mcall.h
- src/hal/arch/cluster/riscv32-cluster/boot.S
- src/hal/arch/cluster/riscv32-cluster/clint.c
- src/hal/arch/cluster/riscv32-cluster/event.c
- src/hal/arch/cluster/riscv32-cluster/machine.c
- src/hal/arch/core/rv32i/core.c
- src/hal/arch/core/rv32i/ivt.c
- src/hal/arch/core/rv32i/machine.c
- src/hal/core/interrupt.c
Description
In this Pull Request, I introduce support for Inter-Processor Interrupts (IPIs) in the RISC-V 32-Bit Cluster famility.
Related Issues
- [[riscv32-cluster] Event Interface](https://github.com/nanvix/hal/issues/326)
> [riscv32-cluster] Support for IPIs

- include/arch/core/or1k/mmu.h
- include/arch/core/or1k/types.h
- src/hal/arch/core/or1k/mmu.c
Description
This PR implements a series of MMU extensions proposed in #276, that basically allows us to map pages and set/unset some flags within the page table and page directory entry.
It's important to note that although the huge pages support have been introduced here, this feature won't work until the HAL TLB handler is changed in order to detect 1-level page table and thus retrieve the huge page mapped into the page directory. This is necessary in order to work for both OpenRISC and MPPA targets, since they have a software-defined TLB.
Related Issues
[Extensions for MMU Interface](https://github.com/nanvix/hal/issues/276)
> [or1k] Enhancement: Extensions for MMU Interface

- include/arch/core/rv32gc/asm.h
- include/arch/core/rv32gc/trap.h
- src/hal/arch/core/rv32gc/hooks.S
- src/test/main.c
Description
In this Pull Request, I re-enable kernel calls rv32gc cores, by emulating them as normal function calls.
Related Issues
- [[rv32gc] Trap Interface](https://github.com/nanvix/hal/issues/227)
> [rv32gc] Re-Enabling Trap Interface

- include/arch/cluster/optimsoc-cluster.h
- include/arch/cluster/optimsoc-cluster/_optimsoc-cluster.h
- include/arch/cluster/optimsoc-cluster/clock.h
- include/arch/cluster/optimsoc-cluster/cores.h
- include/arch/cluster/optimsoc-cluster/memmap.h
- include/arch/cluster/optimsoc-cluster/memory.h
- include/arch/cluster/or1k-cluster/_or1k-cluster.h
- include/arch/cluster/or1k-cluster/cores.h
- include/arch/cluster/or1k-cluster/memmap.h
- include/arch/cluster/or1k-cluster/memory.h
- include/arch/core/mor1kx.h
- include/arch/core/mor1kx/clock.h
- include/arch/core/or1k/cache.h
- include/arch/core/or1k/ompic.h
- include/arch/core/or1k/regs.h
- include/arch/core/or1k/tlb.h
- include/arch/core/or1k/trap.h
- include/nanvix/hal/cluster/_cluster.h
- include/nanvix/hal/core/_core.h
- src/build/processor/makefile.optimsoc
- src/hal/arch/cluster/optimsoc-cluster/_cluster.S
- src/hal/arch/cluster/optimsoc-cluster/boot_code.S
- src/hal/arch/cluster/optimsoc-cluster/boot_data.S
- src/hal/arch/cluster/optimsoc-cluster/cluster.c
- src/hal/arch/cluster/optimsoc-cluster/event.c
- src/hal/arch/cluster/optimsoc-cluster/memory.c
- src/hal/arch/cluster/optimsoc-cluster/ompic.c
- src/hal/arch/cluster/or1k-cluster/boot_code.S
- src/hal/arch/core/or1k/tlb.c
Description
Although the OpTiMSoC and qemu-openrisc shares a great amount of things, it's important to keep separate each cluster for a couple of reasons, like memory map, devices and so on. Keeping things apart also gives us greater freedom to make individual modifications to each cluster without changing the other. Although there are repeated files, they constitute the smallest part of the system, since the main part is defined in the core, not in the cluster.
Therefore, this PR creates a cluster for the OpTiMSoC target, in order to make things more organized and simple.
Related Issues
- [[optimsoc-cluster] Memory Interface](https://github.com/nanvix/hal/issues/286)
> [optimsoc] Memory Interface

- include/arch/core/k1b/tlb.h
In this PR, I repair some field masks of TLB initialization macro
where previously they were being done with one less byte compared to
the actual size of the field causing a loss of information.
> [k1b] Bugfix: TLB initializer

- include/arch/cluster/optimsoc-cluster/clock.h
- include/arch/cluster/or1k-cluster/clock.h
- include/arch/core/mor1kx/clock.h
- include/arch/core/or1k/clock.h
- src/hal/arch/core/or1k/clock.c
Description
This PR fixes the issue #345 by using the frequency supplied to the `clock_init` and `or1k_clock_init` functions.
Related Issues
[[or1k] Clock Interface Ignores Supplied Frequency](https://github.com/nanvix/hal/issues/345)
> [or1k] Using the Frequency Supplied to Initialize Clock

- include/arch/core/k1b/asm.h
- src/hal/arch/core/k1b/hooks.S
- src/test/core/arch/k1b.S
Description
Previously, we were trashing the context when handling an exception by saving bad values of r0 and r1 in the context structure, even though they were already correctly saved. In this commit, I fix this bug.
> [k1b-core] Trashing Context in Exception

- include/arch/cluster/k1b-cluster/memory.h
- include/arch/cluster/or1k-cluster/memory.h
- include/arch/core/k1b/tlb.h
- include/arch/core/or1k/tlb.h
- include/nanvix/hal/cluster/memory.h
- include/nanvix/hal/core/tlb.h
- src/hal/arch/cluster/k1b-cluster/memory.c
- src/hal/arch/cluster/or1k-cluster/memory.c
- src/hal/arch/core/k1b/tlb.c
- src/hal/arch/core/or1k/tlb.c
- src/hal/cluster/memory.c
Description
In this PR, I remove the responsibility of architecture to deal with some common functions that operate on the TLB by abstracting them to the abstraction level of the Cluster.
The following functions have been abstracted:
- `tlb_lookup_vaddr()`
- `tlb_lookup_paddr()`
- `tlb_write()`
- `tlb_inval()`
However, note that for supporting the abstractions I needed to create some auxiliary functions, both in the AL Cluster and in the Core AL. Because of this, assess whether I abstract some parts correctly.
Related Issues
- [[hal] Plataform Independent TLB Management](https://github.com/nanvix/hal/issues/378)
> [hal] Enhancement: Independent TLB implemention

- include/arch/core/i486/int.h
- include/arch/core/k1b/int.h
- include/arch/core/or1k/int.h
- include/arch/core/rv32gc/int.h
- include/arch/core/rv32gc/lpic.h
- include/nanvix/hal/cluster/event.h
- src/hal/core/interrupt.c
Description
So far, HAL does not have any features that relies on Event Handlers, i.e: IPI Interrupts, in this way, it was not possible to receive generic IPI interrupts nor define a user-space handler for it, as occurs with timer interrupts.
For architectures that supports HW Events but do not have IPI interrupts, I insert a dummy `IPI_INTERRUPT` that does not belong to any valid interrupt (and will not be registered as a valid interrupt), for the rest (OpenRISC), a valid `IPI_INTERRUPT` maps to the OMPIC IRQ which in turn registers a generic pre-handler called `do_event` for such arch, which optionally call a user-space defined event in the function `event_handler`.
In addition, following the same approach as `do_clock`, a function called `event_reset` was defined, which …
> [hal] Enhancement: Event Handler

- include/arch/cluster/optimsoc-cluster.h
- include/arch/cluster/optimsoc-cluster/event.h
- include/arch/cluster/optimsoc-cluster/memory.h
- include/arch/cluster/or1k-cluster/event.h
- include/arch/cluster/or1k-cluster/memory.h
- include/arch/core/or1k/int.h
- src/hal/arch/cluster/or1k-cluster/event.c
- src/hal/arch/cluster/or1k-cluster/ompic.c
- src/hal/arch/core/or1k/hooks.S
- src/hal/arch/core/or1k/int.c
Description
Until now, the OpenRISC architecture was relying on a busy waiting approach to handling Events. For a more reliable approach, the use of Inter-Processor Interrupts was necessary.
This PR, in turn, introduces the use of OMPIC device for OpenRISC targets, which is, in fact, the appropriate way to handle Events.
Related Issues
[[or1k-cluster] Blocking Events](https://github.com/nanvix/hal/issues/376)
---------------------------------------
[[hal] Enhancement: Event Handler](https://github.com/nanvix/hal/pull/411)
> [or1k-cluster] Blocking Events

- build/optimsoc/linker/link.ld
- build/qemu-openrisc/linker/link.ld
- include/arch/cluster/optimsoc-cluster/memory.h
- include/arch/cluster/or1k-cluster/memory.h
- include/arch/core/or1k/asm.h
- src/hal/arch/cluster/or1k-cluster/_cluster.S
- src/hal/arch/cluster/or1k-cluster/boot_code.S
- src/hal/arch/cluster/or1k-cluster/boot_data.S
- src/hal/arch/cluster/or1k-cluster/cluster.c
- src/hal/arch/cluster/or1k-cluster/memory.c
Description
It's expected that the BSS section is cleared in the startup, otherwise, unexpected behaviors could arise, this PR fixes it.
Related Issues
- [[hal] BSS Initialization Is Missing](https://github.com/nanvix/hal/issues/231)
> [or1k-core] BSS Initialization Is Missing

- include/arch/cluster/k1b-cluster/cores.h
- include/nanvix/hal/core.h
- src/hal/arch/core/i486/core.c
- src/hal/arch/core/k1b/core.c
- src/hal/arch/core/or1k/core.c
- src/hal/arch/core/rv32gc/core.c
- src/hal/core/core.c
Description
In this PR, I isolate the behavior of halting a core in Core AL because that is architecture independent.
Related Issues
- [[hal] Generic Power Off](https://github.com/nanvix/hal/issues/399)
> [hal] Generic power off

- src/test/cluster/cores.c
- src/test/makefile
Description
This PR disable the stress tests when the HAL is build by default, if built with the environment var `__ENABLE_STRESS_TESTS` set, the stress tests will be enabled again.
Related Issues
- [[build] Disable Stress Tests In Default Build](https://github.com/nanvix/hal/issues/416)
> [hal] Disable Stress Tests in Default Build

- include/arch/cluster/optimsoc-cluster/memory.h
Description
In the latest PR related to TLB management (#408) the changes introduced do not take into account the OpTiMSoC target, which causes some failures during the system building.
This PR, introduces the provided interface as well as synchronizes the optimsoc cluster memory interface with the base or1k cluster.
> [optimsoc-cluster] Bug Fix: Provided Interface Not Defined

- src/hal/arch/cluster/or1k-cluster/event.c
Description
In the issue #426 was realized that the optimsoc target does not have the OMPIC device by default, this PR, in turn, selectively uses the OMPIC approach only on or1k-cluster targets, while the optimsoc targets use the busy-waiting approach, as it was before.
While the desirable solution would be introduce the OMPIC support to the OpTiMSoC source tree, while this does not happen, our best option is to have the busy-waiting approach again.
Related Issues
[[optimsoc-cluster] OMPIC Not Present in OpTiMSoC](https://github.com/nanvix/hal/issues/426)
> [optimsoc-cluster] Using the Busy-Waiting Approach in the Events

- src/hal/upcall.c
- src/test/core/upcall.c
Description
In this PR, I fix the align of the stack pointer on `upcall_forge()`.
Related Issues
- [[hal] Badly aligned stack pointer on upcall forge](https://github.com/nanvix/hal/issues/435)
> [hal] Wrong Padding When Forging an Upcall

- include/arch/core/mor1kx/perf.h
- src/hal/arch/core/mor1kx/perf.c
Description
This PR implements the `perf_restart()` function as described in the issue #438.
Related Issues
- [[hal] Extensions for Performance Monitoring Interface](https://github.com/nanvix/hal/issues/438)
> [optimsoc] Performance Counters Restart

- src/hal/arch/target/mppa256/bindesc.c
Description
In this PR, I fix the TLB initializer macros that were with some parameters changed and had incomplete values.
Related Issues
- [[mppa256] IO Clusters Aren't Working](https://github.com/nanvix/hal/issues/447)
> [k1b] Bugfix: Wrong Static TLBs entries

- include/nanvix/cc.h
- src/test/cluster/cores.c
- src/test/core/interrupt.c
Description
The GCC was producing wrong code if the optimization flags were enabled, because the condition variables were changed in other contexts other than the functions they were in, so the compiler was producing an infinite loop instead of checking the value of the variable at all times.
To fix, the 'volatile' qualifier is needed, to tell the compiler that the variable can be changed in other contexts. In addition, the 'always_inline' attribute was removed since it was producing incorrect code for the OpenRISC architecture.
> [hal] Bug Fix: Optimization Produces Wrong Code

- build/optimsoc/make/makefile.cflags
- build/qemu-openrisc/make/makefile.cflags
Description
To make the system optimized in the qemu-openrisc and OpTiMSoC targets, this PR introduces the optimization flags for both. However, it is important to note that -O1, -O2, and -O3 breaks the system for OpenRISC, which made it necessary to enable supported flags manually.
Related Issues
[[build] Cannot Enable Level 3 Compilier Optimizations](https://github.com/nanvix/hal/issues/445)
---------------------------------------
[[hal] Bug Fix: Optimization Produces Wrong Code](https://github.com/nanvix/hal/pull/449)
> [openrisc] Optimization Flags

- include/arch/core/or1k/cache.h
- src/hal/arch/cluster/or1k-cluster/boot_code.S
Description
This PR implements the functions `icache_setup()` and `dcache_setup()` found on issue #232. Although currently none of the targets supports cache, the routines above are smart enough to verify if the cache is present and only if, the cache will be enabled properly.
Related Issues
[[hal] Extensions for Memory Cache Interface](https://github.com/nanvix/hal/issues/232)
> [openrisc] Enhancement: Cache Setup

- build/optimsoc/linker/link.ld
- build/qemu-openrisc/linker/link.ld
- include/arch/cluster/optimsoc-cluster/memory.h
- include/arch/cluster/or1k-cluster/memory.h
Description
This PR adds the bootstrap variables required to the linker scripts for both qemu-openrisc and optimsoc targets.
Related Issues
[[hal] Platform Independent Link Variables](https://github.com/nanvix/hal/issues/410)
> [openrisc] Bootstrap Link Variables

- build/unix64/make/makefile
- include/arch/core/linux64/cache.h
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/arch/core/linux64-core/cache.c
- src/test/main.c
Description
In this PR we introduce the Memory Cache Interface for the UNIX 64-bit target.
Related Issues
- [[linux64-core] Memory Cache Interface](https://github.com/nanvix/hal/issues/444)
- [[hal] Extensions for Memory Cache Interface](https://github.com/nanvix/hal/issues/232)
> [unix64] Feature: Memory cache interface and extensions

- include/arch/core/i486/spinlock.h
- include/arch/core/k1b/spinlock.h
- include/arch/core/or1k/spinlock.h
- include/arch/core/rv32gc/spinlock.h
Descrption
Previously, in the spinlock_unlock() operation we were flushing/invalidating the cache in before releasing the lock. As a consequence, the semantics of the unlock operation would not be correct.
Related Issues
- [[mppa256] Startup Fence Blocks Master Core](https://github.com/nanvix/hal/issues/476)
> [hal] Bad Cache Inval in Spinlock Release

- src/hal/arch/cluster/or1k-cluster/cluster.c
Description
In order to work properly, the spinlock for master core must be initialized as unlocked, as it already occurs in other platforms like qemu-riscv32 and mppa256.
This PR fixes it, by initializing the spinlocks as expected by the system.
> [openrisc-cluster] Wrong Spinlock Initialization

- include/arch/core/i486/pmio.h
Adding io input functions for 8/16/32 bits and output functions for 16/32 bits using examples from OSDev.
Untested.
> [qemu-x86] I/O Functions for 8/16/32 bits

- include/arch/cluster/k1b-cluster.h
- include/arch/cluster/linux64-cluster.h
- include/arch/cluster/optimsoc-cluster.h
- include/arch/cluster/optimsoc-cluster/timer.h
- include/arch/cluster/or1k-cluster.h
- include/arch/cluster/or1k-cluster/timer.h
- include/arch/cluster/riscv32-cluster.h
- include/arch/cluster/riscv32-cluster/timer.h
- include/arch/cluster/x86-cluster.h
- include/arch/cluster/x86-cluster/timer.h
- include/arch/core/i486/timer.h
- include/arch/core/mor1kx/timer.h
- include/arch/core/or1k/timer.h
- include/nanvix/hal/cluster/timer.h
- src/hal/arch/core/i486/timer.c
- src/hal/arch/core/or1k/timer.c
- src/hal/core/interrupt.c
Description
This PR adds the timer extensions described in #420 for all currently supported targets, which means that for all architectures that do not have a separate hardware clock counter (like the Time-Stamp Counter in x86), a counter introduced by the HAL will be used instead.
Related Issues
- [[hal] Timer Interface Extensions](https://github.com/nanvix/hal/issues/420)
> [hal] Timer Interface Extensions

- build/qemu-x86/linker/link.ld
- include/arch/cluster/x86-cluster/cores.h
- include/arch/cluster/x86-cluster/memmap.h
- include/arch/cluster/x86-cluster/memory.h
- include/arch/core/i486/asm.h
- include/arch/core/i486/mmu.h
- include/arch/core/i486/spinlock.h
- src/hal/arch/cluster/x86-cluster/_cluster.S
- src/hal/arch/cluster/x86-cluster/boot.S
- src/hal/arch/cluster/x86-cluster/cluster.c
- src/hal/arch/cluster/x86-cluster/memory.c
- src/hal/arch/core/i486/mmu.c
Description
In order to proceed with #371, the x86-cluster needs some refactor from before starting with a platform independent setup, since x86 is way outdated comparing with another clusters.
Thus, this PR updates the x86-cluster at the same point as the other clusters.
Related Issues
- [[hal] Platform Independent Link Variables](https://github.com/nanvix/hal/issues/410)
- [[hal] Platform Independent Setup for Virtual Memory](https://github.com/nanvix/hal/issues/371)
> [x86-cluster] Enhancing Virtual Memory Setup

- include/nanvix/hal/target/mailbox.h
Description
This PR removes all the dummy routines for mailbox interfsce in the HAL, since if the HAL does not support mailboxes, there is no need to implement them.
> [ha] Mailbox Dummy Interfaces Are No Longer Needed

- include/arch/target/kalray/mppa256/mailbox.h
- include/arch/target/kalray/mppa256/portal.h
- include/arch/target/kalray/mppa256/sync.h
- include/arch/target/unix64/unix64/mailbox.h
- include/arch/target/unix64/unix64/portal.h
- include/arch/target/unix64/unix64/sync.h
- include/nanvix/hal/target/mailbox.h
- include/nanvix/hal/target/portal.h
- include/nanvix/hal/target/sync.h
- src/hal/hal.c
In this PR, I provide initialization functions for the Sync, Mailbox and Portal interface though with some caveats.
- **MPPA-256:** All structures are statically initialized, so the setup functions don't have operations.
- **unix64:** I provide only the definition and a dummy prototype, so this still must be implemented. 
This PR doesn't complete the follow issue.
Related Issues
- [[hal] Dynamic Initialization for Sync, Mailbox and Portal](https://github.com/nanvix/hal/issues/527)
> [hal] Feature: Dynamic Initialization for Sync, Mailbox and Portal

- include/nanvix/hal/processor/noc.h
- src/hal/arch/target/mppa256/sync.c
- src/test/main.c
- src/test/target/mailbox.c
- src/test/target/portal.c
- src/test/target/sync.c
In this PR, I fix the following bugs:
- Sync: adds validation function to sync abstraction to check a node list doesn't contain duplicated nodes, contain only valid nodes and if the local node is included.
- test/main.c: I add a `#ifdef` check to call `test_portal()` on target tests.
- Dummy Cluster/Noc Interface: Wrong parameters' name.
> [mppa256] Fixing Regression Tests on Target AL

- include/arch/core/k1b/cache.h
In this PR, I remove the `__builtin_k1_dflush` call because that it isn't implemented for the k1b architecture, only for k1a.
Even though in the documentation, it appears that this function exists for k1b, compilation generates both implicit invocation errors and no implementation found.
The following snippet was also found in the headers:
```
/* DFLUSHL is K1A only */
extern void __builtin_k1_dflush(void);
/* DFLUSHLL is K1A only */
extern void __builtin_k1_dflushl(const void *addr);
```
> [k1b] Bugfix: Removes __builtin_k1_dflush call.

- include/arch/processor/bostan/noc.h
- include/arch/processor/linux64/noc.h
- include/nanvix/hal/processor/noc.h
- src/hal/arch/processor/bostan/noc.c
- src/hal/arch/processor/linux64/noc.c
- src/hal/arch/target/unix64/mailbox.c
- src/hal/arch/target/unix64/portal.c
- src/hal/arch/target/unix64/sync.c
- src/test/processor/cnoc.c
- src/test/processor/dnoc.c
- src/test/processor/noc.c
In this PR, I introduce the concept of exchange of node number. The idea comes from the multiples node numbers available inside an IO cluster of the MPPA-256. Thus, the client application can use all those numbers without the HAL needs to handler implicitly.
> [hal] Exchange of Node Number

- src/hal/arch/target/unix64/mailbox.c
- src/hal/arch/target/unix64/portal.c
- src/hal/arch/target/unix64/sync.c
In this PR was added the `nanvix` prefix on the underlying resources for sync, mailboxes and portals.
[[unix64] Rename Sync, Mailboxes & Portals](https://github.com/nanvix/hal/issues/535)
> [unix64] Rename Sync, Mailboxes & Portals

- include/arch/processor/i486-qemu/clusters.h
- include/arch/processor/i486-qemu/noc.h
- include/arch/processor/optimsoc/clusters.h
- include/arch/processor/optimsoc/noc.h
- include/arch/processor/riscv32/clusters.h
- include/arch/processor/riscv32/noc.h
- include/nanvix/hal/processor/_processor.h
- include/nanvix/hal/processor/clusters.h
- include/nanvix/hal/processor/noc.h
- src/hal/arch/processor/optimsoc4/clusters.c
- src/hal/arch/processor/optimsoc4/noc.c
- src/hal/arch/processor/riscv32/clusters.c
- src/hal/arch/processor/riscv32/noc.c
- src/hal/arch/processor/x86/clusters.c
- src/hal/arch/processor/x86/noc.c
- src/hal/hal.c
- src/test/main.c
- src/test/processor/clusters.c
- src/test/processor/noc.c
Description
Since some targets needs to define the NoC and Processor interface inside microkernel, there is a need to implement a generic interface (for those that lacks NoC and Multicluster) for each target, in order to re-define them inside microkernel.
It's important to note that now the HAL does not launch the tests for targets that lack `PROCESSOR_IS_MULTICLUSTER` and `PROCESSOR_HAS_NOC`, this is necessary to let those targets implement the `cluster_*` and `processor_*` function families in higher level, i.e: microkernel, hence, these tests should be implemented and executed in microkernel.
> [hal] Enhancement: Dummy Implementation of NoC and Clusters

- include/arch/target/kalray/mppa256/portal.h
- include/arch/target/unix64/unix64/portal.h
- include/nanvix/hal/target/portal.h
- src/hal/arch/target/mppa256/portal.c
- src/hal/arch/target/unix64/portal.c
- src/test/target/portal.c
In this PR, were updated the constants provided by the Hal related to the number of logic ports exported to the Microkernel in the Portal facility. Also, small changes were made on the communication functions returns to make retries easier in above layers.
[#552 - Portal Logic Ports Support](https://github.com/nanvix/hal/issues/552)
> [hal] Portal ports support

- include/arch/processor/bostan/noc/dtag.h
- src/hal/arch/processor/bostan/ctag.c
- src/hal/arch/processor/bostan/dtag.c
- src/hal/arch/target/mppa256/mailbox.c
- src/hal/arch/target/mppa256/sync.c
In this PR, I fix the interrupt handlers of control and data NoCs. The handler performs several checks to ensure that no interruptions have been missed. This bug directly influenced some mailbox benchmarks.
> [mppa256] Losing NoC Interrupts

- include/arch/processor/bostan/noc.h
- include/arch/processor/linux64/noc.h
- include/nanvix/hal/processor/noc.h
- src/hal/arch/processor/bostan/noc.c
- src/hal/arch/processor/linux64/noc.c
- src/hal/arch/target/unix64/portal.c
- src/hal/arch/target/unix64/sync.c
- src/test/processor/cnoc.c
- src/test/processor/dnoc.c
- src/test/processor/noc.c
In this PR, I remove the dependency of the coreid to get the local `nodenum`. Also, I remove the unnecessary `processor_node_set_num` and its redundant code.
> [processor] Drop Node Number Exchange

- src/hal/arch/target/mppa256/mailbox.c
In this PR, the `mppa256_mailbox_aread` now returns `ENOMSG` error when there's no message available. This prevent upper layers from waiting for a intra-cluster message.
> [mppa256] Mailbox Non-blocking Read

- src/hal/arch/target/unix64/mailbox.c
- src/test/stress/mailbox.c
In this PR, the Mailbox Read / Write now return errors when a communication operation doesn't met the requirements to occur at the specified moment, instead of blocking until they are reached.
This is an attempt of solving the Unix Microkernel freezing problem. Need more tests to ensure it.
> [unix64] Mailbox Non-blocking Read/Write

- include/arch/processor/bostan/noc.h
- include/arch/processor/bostan/noc/ctag.h
- include/arch/processor/bostan/noc/dma.h
- include/arch/target/kalray/mppa256/sync.h
- include/arch/target/unix64/unix64/sync.h
- include/nanvix/hal/target/sync.h
- src/hal/arch/processor/bostan/ctag.c
- src/hal/arch/processor/bostan/dma.c
- src/hal/arch/processor/bostan/noc.c
- src/hal/arch/target/mppa256/sync.c
- src/hal/arch/target/unix64/sync.c
- src/hal/target/sync.c
In this PR, I change de sync system to support the differents node lists in an independent manner. The interface still the same where the main changes occurred in Unix and MPPA-256 implementation. An important point is the abstraction of the checks like mailbox/portal targets.
**Obs.: Not tested on MPPA-256 yet.**
_____
- A signal message is a [hash](https://github.com/nanvix/hal/blob/enhancement-sync-refactor/src/hal/arch/target/unix64/sync.c#L51) as follow:
``` c
struct hash
{
uint64_t source    :  5;
uint64_t type      :  1;
uint64_t master    :  5;
uint64_t nodeslist : 20;
uint64_t unused    : 33;
};
```
- Each node has a unique mqueue to receive signal messages;
- Wait operation will read a message and updates the barrier hash (node list of nodes that sent a signal) and will try …
> [unix64]  Sync Facility Refactor

- include/arch/target/kalray/mppa256/mailbox.h
- include/arch/target/kalray/mppa256/portal.h
- include/arch/target/unix64/unix64/mailbox.h
- include/arch/target/unix64/unix64/portal.h
- include/nanvix/hal/target/mailbox.h
- include/nanvix/hal/target/portal.h
- include/nanvix/hal/target/sync.h
- src/hal/target/portal.c
In this PR, I solved two problems:
- Introduces constants to define each part of a mailbox/portal message, i.e., header (reserved) and data sizes. The size of the data in the portal message is still 8 KB, as this eliminates the need to break data with sizes multiple of two, much used by the internal systems of Nanvix.
- Lack of verification of the maximum size of messages sent by the portal.
[[hal] Check for Read/Write Size in Portal Operations #557](https://github.com/nanvix/hal/issues/557)
> [target] Missing Constants and Checks

- build/qemu-riscv32/make/makefile
- include/nanvix/hal/cluster.h
- src/hal/cluster/cluster.c
- src/test/cluster/cores.c
In this PR, I introduce a pre-reset phase of the core to allow the upper layers to indicate when a core is close to being reset.
For this, I added a new state called `CORE_ZOMBIE`. When trying to call `core_start()` on a core that is in this state, a busy-wait is performed until the core enters the `CORE_RESETTING` state.
**Obs: `core_release` call is prerequisite of the `core_reset` call.**
- Closes https://github.com/nanvix/hal/issues/586
> [cluster] Core Reset in Two Phases

- src/hal/arch/target/mppa256/sync.c
In this PR, I increase the number of bits used to store the nodes list and the barrier in the sync of the MPPA-256.
[Sync barrier variable using fewer bits than the number of nodes #601](https://github.com/nanvix/hal/issues/601)
> [noc] Sync Barrier Variable Uses Less Bits Than the Number of Nodes

- include/arch/target/kalray/mppa256/portal.h
- include/arch/target/kalray/mppa256/sync.h
- include/arch/target/unix64/unix64/sync.h
- makefile
- src/hal/arch/target/mppa256/portal.c
- src/hal/arch/target/mppa256/sync.c
- src/hal/arch/target/unix64/boot.c
- src/hal/arch/target/unix64/portal.c
- src/hal/arch/target/unix64/sync.c
- src/hal/arch/target/unix64/target.c
- src/hal/target/portal.c
- src/hal/target/sync.c
- src/test/stress/api.c
- src/test/target/portal.c
- src/test/target/sync.c
In this PR, I add __NANVIX_IKC_USES_ONLY_MAILBOX flag that disables sync/portal implementation.
> [target] Support for ONLY_MAILBOX Mode

- include/arch/processor/bostan/noc.h
- include/arch/processor/bostan/noc/ctag.h
- src/hal/arch/processor/bostan/ctag.c
- src/hal/arch/processor/bostan/dtag.c
- src/hal/arch/target/mppa256/mailbox.c
- src/hal/arch/target/mppa256/portal.c
- src/hal/arch/target/mppa256/sync.c
In this PR, I fix when we need to mask interrupts inside the NoC handlers, eliminating undesired nested interrupts.
Also, I standardized how we verify the loss of interrupts. This new way verifies both NoC interrupts (CNoC and DNoC) eliminating interference between NoC handlers and critical regions.
[[target] Make Sync use Only one C-NoC TX](https://github.com/nanvix/hal/issues/606)
> [mppa256] Remove Nested Interrupts and Interference Between NoC Handlers

- include/arch/core/linux64/types.h
In this PR, I fix the bad width for half-words and words in the Unix64 target.
- Fixes #608
> [core-al] Bad Width for Words

- include/arch/core/i486/ctx.h
- include/arch/core/k1b/ctx.h
- include/arch/core/linux64/ctx.h
- include/arch/core/or1k/ctx.h
- include/arch/core/rv32gc/ctx.h
- src/test/core/exception.c
In this PR, I define non-destructive exception tests for most architectures. The current version has the following behaviors:
- `unix64`: Does not support non-destructive tests because of the way that we simulate that.
- `rv32gc`:  illegal instruction dealt with by increasing the program counter of the context. **But it is not currently supported because the issue #611**
- `or1k`: illegal instruction dealt with by increasing the program counter of the context.
- `Other architectures`: Access to an invalid address handled by changing the address to a local static variable (DTLB exception).
This enhancement highlight the not alignment of context structures (issue #612) that is fixed by this PR.
- Cites #611
- Closes #612
> [test] Non-Destructive Exception Test

- src/test/core/upcall.c
In this PR, I disable but do not remove the tests from the upcall because they are not stable in the MPPA-256.
According to issue #614, when we correctly restored the context, the`test_upcall_issue` test introduced a deadlock. We still don't know exactly why, but the manipulation and change of stack performed in the test introduces undefined behavior to the system.
> [test] Bugfix: Disable upcall tests because it is unstable.

- include/nanvix/hlib.h
- src/hal/hlib/kpanic.c
- src/hal/hlib/kprintf.c
Changes kprintf to use kvsnprintf instead of ksvprintf. By doing this, we can limit the size of characters the formatting function will place inside the buffer and block outputs that would overflow the buffer. If an output were to overflow the buffer, it would be truncated.
This closes #364 
This depends on the addition of the __vsnprintf function on the barelib. Without it, build errors will occur.
> [hlib] Block Long Prints

- include/arch/core/k1b/int.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/ivt.c
In this PR, I implement our own interrupt dispatcher and configure that directly on mOS scoreboard. This made it possible to remove BSP dependency.
I also map interrupt code to correspond to the IRQ code, which is the identifier used by the hardware to identify the interrupts.
> [k1b-core] Drop the Dependency on BSP Interrupt Dispatcher

- include/arch/core/i486.h
- include/arch/core/k1b.h
- include/arch/core/k1b/asm.h
- include/arch/core/k1b/ctx.h
- include/arch/core/k1b/mOS.h
- include/arch/core/linux64.h
- include/arch/core/mor1kx.h
- include/arch/core/or1k.h
- include/arch/core/rv32gc.h
- include/nanvix/hal/core/context.h
- src/hal/arch/core/k1b/ctx.c
- src/hal/arch/core/k1b/hooks.S
- src/hal/core/context.c
- src/test/cluster/cores.c
- src/test/core/core.c
In this PR, I introduce the interface to create and exchange execution contexts. Besides the default interface, the incoming changes already bring the implementation for MPPA-256 architecture.
This feature is verified by two unit tests:
- Creation of a context
- Context switching and restoration using three levels of contexts.
Mention #620
> [core] Introduce Context Switching Mechanism

- src/test/main.c
In this PR, we change back the main of tests to the old version only on Unix, i.e., only master cluster runs all tests available. We need to make this because if both clusters run all tests, they cannot synchronize on communication tests for some sake.
Mention #633
> [test] Unit Tests Get Stuck in Unix

- include/arch/cluster/linux64-cluster/cores.h
In this PR, we increase the number of cores in Unix64 from 4 to 5, to permit the Nanvix System to include a Name Service Daemon in each Compute Cluster without incurring in cores starvation.
> [cores][unix64] Linux Cores Num

- include/arch/core/i486/int.h
- include/arch/core/i486/lpic.h
- include/arch/core/k1b/int.h
- include/arch/core/k1b/lpic.h
- include/arch/core/linux64/int.h
- include/arch/core/or1k/int.h
- include/arch/core/or1k/lpic.h
- include/arch/core/rv32gc/int.h
- include/nanvix/hal/core/interrupt.h
- include/nanvix/hal/section_guard.h
- src/hal/arch/core/i486/lpic.c
- src/hal/arch/core/k1b/lpic.c
- src/hal/arch/core/linux64-core/int.c
- src/hal/arch/core/or1k/lpic.c
- src/hal/cluster/cluster.c
In this PR, I add the `interrupts_get_level` function to all the platforms and use it to enhance the behavior of the section guard. Specifically, the section guard now only changes the interrupt level if the core is on a lower priority level.
Closes #636
> [core] Add a Getter to Interrupt Level and Use It on Section Guards

- src/hal/arch/cluster/k1b-cluster/ipi.c
- src/hal/arch/core/k1b/ctx.c
- src/hal/arch/core/k1b/hooks.S
- src/hal/cluster/event.c
In this PR, I fix the following bugs:
- New context must start with the interrupt disabled
- Use parameters register instead of hard-coded register
- Move the IPI sending to before the event notify so that the core can execute the interrupt before clearing the event and continues its execution.
- Because on the microkernel we have thread migration, I change the lock from core granularity to be global. Moreover, we reevaluate what is the underlying core always that an event is completed.
The following PR must be accepted before the review of this PR:
- Mentions #638
> [k1b-cluster][k1b-core] Bugfix: Fixes on new contexts, assembly and events

- include/arch/core/i486/int.h
- include/arch/core/k1b/int.h
- include/arch/core/linux64/int.h
- include/arch/core/or1k/int.h
- include/arch/core/rv32gc/int.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/interrupt.h
- include/nanvix/hal/core/status.h
- include/nanvix/hal/core/trap.h
- include/nanvix/hal/section_guard.h
- src/hal/arch/core/i486/hooks.S
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/hooks.S
- src/hal/arch/core/rv32gc/hooks.S
- src/hal/core/exception.c
- src/hal/core/interrupt.c
- src/hal/core/status.c
- src/hal/core/trap.c
In this PR, I introduce a managed software structure to track the mode in which the nuclei are running. This feature was introduced because the Section_Guard abstraction in the MPPA masked the interruptions even are inside an interrupt handler. That is, the interrupt control is different from the level of interruptions in the MPPA so required this structure to abstract how we check in which way we are.
> [core] Feature: Tracking execution modes (core status)

- src/hal/arch/target/mppa256/mailbox.c
We are setting value on RX's array instead of TX's on mailbox_open of the MPPA-256.
> [target][mppa256] Bugfix: Setting values on the incorrect array on mailbox_open

- include/arch/core/rv32gc/mregs.h
- include/arch/core/rv32gc/sregs.h
- src/hal/arch/core/rv32gc/hooks.S
I backported all instructions from gcc 1.10 to 1.9.1. That way it's possible to compile and run using the pulp sdk.
> [rv32gc] backporting gcc from 1.10 to 1.9.1 to support pulp sdk
