nanvix/hal

- build/i386-pc/make/makefile
- build/mppa256/make/makefile
- build/or1k-pc/linker/link.ld
- build/or1k-pc/make/makefile
- include/arch/core/or1k/clock.h
- src/hal/arch/core/or1k/clock.c
- src/hal/klib/kvsprintf.c
Some architectures do not support hardware division, thus causing
misbehavior when printing integer formats. In this commit, I have
introduce a selective support for integer printing.
>  Enhancement: Selective Support for Integer Prints

- .gdbinit
- build/i386-pc/make/makefile
- build/or1k-pc/make/makefile
- include/arch/core/i386/cache.h
- include/arch/core/i386/context.h
- include/arch/core/i386/core.h
- include/arch/core/i386/mmu.h
- include/arch/core/i386/types.h
- include/arch/core/k1b.h
- include/arch/core/k1b/core.h
- include/arch/core/k1b/excp.h
- include/arch/core/k1b/mmu.h
- include/arch/core/k1b/types.h
- include/arch/core/or1k.h
- include/arch/core/or1k/core.h
- include/arch/core/or1k/excp.h
- include/arch/core/or1k/mmu.h
- include/arch/core/or1k/tlb.h
- include/arch/core/or1k/types.h
- include/nanvix/hal/core.h
- src/hal/arch/core/i386/boot.S
- src/hal/arch/core/i386/hooks.S
- src/hal/arch/core/or1k/boot_code.S
- src/hal/arch/core/or1k/boot_data.S
- src/test/build/makefile.i386-pc
- src/test/build/makefile.or1k-pc
- tools/run/run-qemu.sh
**Description**
In this pull request, I introduce core types and constants for the Core Interface.
**Related Issues**
- [[hal] Core Interface](https://github.com/nanvix/hal/issues/5)
> Enhancement: Core Types

- include/arch/core/k1b/asm.h
- src/hal/arch/core/k1b/hooks.S
[k1b-core] Enhancement: Fast Procedure Linkage
[k1b-core] Enhancement: Slow Procedure Linkage
> [k1b-core] Enhancement: Procedure Linkage

- src/test/clock.c
- src/test/core.c
- src/test/main.c
This PR introduces the test needed to initialize all slave cores and check if all of them is running properly. The test passed both in or1k-pc and OpTiMSoC (HW).
> [hal] Enhancement: Start Instruction Execution in a Slave Core

- include/nanvix/klib.h
In this commit, I introduce some macro-magic to auto-name reserved
fields of a structure.
> [hal] Enhancement: Auto-Name Reserved Fields

- include/arch/core/k1b/asm.h
- include/nanvix/klib.h
- src/hal/arch/core/k1b/ivt.c
- src/test/arch/k1b.S
- src/test/build/makefile.i386-pc
- src/test/build/makefile.mppa256
- src/test/build/makefile.or1k-pc
- src/test/exception.c
- src/test/main.c
- src/test/makefile
- src/test/test.h
Description
In this commit, I introduce a test driver for the Exception Interface.
Related Issues
- [[hal][test] Unit Tests for Exception Interface](https://github.com/nanvix/hal/issues/3)
> [hal][test]Test Driver for Exception Interface

- include/arch/core/k1b/asm.h
- include/arch/core/k1b/context.h
- include/arch/core/k1b/excp.h
- include/nanvix/klib.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/ivt.c
- src/test/arch/k1b.S
- src/test/build/makefile.i386-pc
- src/test/build/makefile.mppa256
- src/test/build/makefile.or1k-pc
- src/test/exception.c
- src/test/main.c
- src/test/makefile
- src/test/test.h
Description
- Macro for Checking Alignment
- Macro for Truncating Addresses
> [hal][lib] Memory Macros

- include/arch/core/i386/excp.h
- include/arch/core/k1b/asm.h
- include/arch/core/k1b/context.h
- include/arch/core/k1b/excp.h
- include/arch/core/or1k/excp.h
- include/nanvix/hal/core/exception.h
- include/nanvix/klib.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/ivt.c
- src/test/arch/k1b.S
- src/test/build/makefile.i386-pc
- src/test/build/makefile.mppa256
- src/test/build/makefile.or1k-pc
- src/test/exception.c
- src/test/main.c
- src/test/makefile
- src/test/test.h
Description
With this PR I have added the `EXCEPTION_SIZE` to the Exception Interface
Related Issues
- [[hal] Exception Interface](https://github.com/nanvix/hal/issues/9)
- [[k1b] Exception Interface](https://github.com/nanvix/hal/issues/19)
- [[openrisc] Exception Interface](https://github.com/nanvix/hal/issues/20)
- [[x86] Exception Interface](https://github.com/nanvix/hal/issues/21)
> [hal] Adding Exception Size of Exception Interface

- src/test/core.c
This PR introduces the test that initializes one slave core and then suspend and resume, this test helps to find out if the basic communication is working fine. The test passed both in or1k-pc and OpTiMSoC (HW).
> [hal] Enhancement: Suspend and Resume from Master

- include/arch/core/i386/mmu.h
- include/arch/core/i386/types.h
- include/arch/core/k1b/mmu.h
- include/arch/core/k1b/types.h
- include/arch/core/or1k/mmu.h
- include/arch/core/or1k/types.h
- include/nanvix/hal/core/mmu.h
Description
In this PR I introduce additional memory types and constants to the MMU Interface
Related Issues
- [[hal] MMU Interface](https://github.com/nanvix/hal/issues/35)
- [[openrisc] MMU Interface](https://github.com/nanvix/hal/issues/37)
- [[x86] MMU Interface](https://github.com/nanvix/hal/issues/38)
- [[k1b] MMU Interface](https://github.com/nanvix/hal/issues/36)
> [hal Exporting Memory Types

- include/arch/core/i386.h
- include/arch/core/i386/idt.h
- include/arch/core/i386/int.h
- include/arch/core/i386/trap.h
- include/arch/core/k1b.h
- include/arch/core/k1b/trap.h
- include/arch/core/or1k.h
- include/arch/core/or1k/trap.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/trap.h
- src/hal/arch/core/i386/hooks.S
- src/hal/arch/core/i386/idt.c
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/hooks.S
- src/test/syscalls.c
Description
In this commit, I introduce the Trap Interface.
Related Issues
- [[hal] Trap Interface](https://github.com/nanvix/hal/issues/25)
- [[x86] Trap Interface](https://github.com/nanvix/hal/issues/28)
- [[k1b] Trap Interface](https://github.com/nanvix/hal/issues/27)
- [[openrisc] Trap Interface](https://github.com/nanvix/hal/issues/26)
> [hal] Trap Interface

- include/arch/core/i386/spinlock.h
Description
In this PR, I introduce the implementation of the Sinlock Interface for i386 cores.
Related Issues
- [[x86] Spinlock Interface](https://github.com/nanvix/hal/issues/14)
> [i386-core] Feature: Spinlock Interface

- src/test/main.c
- src/test/syscalls.c
- src/test/test.h
Description
In this PR I introduce the test driver for the Trap Interface, and additionally one unit test (Issue a Kernel Call with Five Arguments).
Related Issues
- [[hal][test] Unit Tests for Trap Interface](https://github.com/nanvix/hal/issues/126)
> [hal][test] Unit Test Driver for Trap Interface

- include/arch/core/or1k/context.h
- src/hal/hal.c
Description
In this PR, I introduce dynamic size checking for the exception and context structures.
> Size Checking of Exception and Context Structures

- include/nanvix/klib.h
- src/hal/log.c
- src/test/clock.c
- src/test/interrupt.c
- src/test/main.c
Description
In this PR,  introduce unit tests for the Hardware Interrupt Interface.
Related Issues
- [[hal][test] Unit Tests for Hardware Interrupt Interface](https://github.com/nanvix/hal/issues/4)
> [hal][test] Unit Tests for Hardware Interrupt Interface

- src/test/exception.c
Description
In this PR,  introduce unit tests for the Exception Interface.
Related Issues
- [[hal] Exception Interface](https://github.com/nanvix/hal/issues/9)
> [hal][test] Unit Tests for Exception Interface

- README.md
> Adding a README File

- include/arch/core/i486/asm.h
- include/arch/core/i486/gdt.h
- include/arch/core/i486/upcall.h
- include/arch/core/k1b/asm.h
- include/arch/core/k1b/upcall.h
- include/arch/core/or1k/asm.h
- include/arch/core/or1k/upcall.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/upcall.h
- src/hal/arch/core/i486/_upcall.S
- src/hal/arch/core/i486/hooks.S
- src/hal/arch/core/k1b/_upcall.S
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/_upcall.S
- src/hal/arch/core/or1k/hooks.S
- src/hal/upcall.c
- src/test/arch/i486.S
- src/test/arch/k1b.S
- src/test/arch/or1k.S
- src/test/build/makefile.i486-pc
- src/test/build/makefile.or1k-pc
- src/test/main.c
- src/test/syscalls.c
- src/test/upcall.c
Description
In this PR I introduce unit tests for the Upcall Interface.
Related Issues
- [[hal][test] Unit Tests for Upcall Interface](https://github.com/nanvix/hal/issues/59)
> [hal][test] Unit Tests for Upcall Interface

- include/arch/core/i486/asm.h
- include/arch/core/i486/gdt.h
- include/arch/core/i486/upcall.h
- include/arch/core/k1b/asm.h
- include/arch/core/k1b/upcall.h
- include/arch/core/or1k/asm.h
- include/arch/core/or1k/upcall.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/upcall.h
- src/hal/arch/core/i486/_upcall.S
- src/hal/arch/core/i486/hooks.S
- src/hal/arch/core/k1b/_upcall.S
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/_upcall.S
- src/hal/arch/core/or1k/hooks.S
- src/hal/upcall.c
Description
In this PR we introduce the implementation of the Upcall Interface for all supported targets.
Related Issues
- [[hal] Upcall Interface](https://github.com/nanvix/hal/issues/10)
> [hal] Upcall Interface Implementation

- include/nanvix/hal/core/trap.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/hooks.S
- src/test/syscalls.c
Description
In this PR I add unit tests for the Trap Interface.
- [[k1b-core] Save Preserved Regs in Trap](https://github.com/nanvix/hal/pull/168)
- [[k1b-core] Bad Trap Call Arguments](https://github.com/nanvix/hal/pull/169)
Related Issues
- [[hal][test] Unit Tests for Trap Interface](https://github.com/nanvix/hal/issues/126)
- [[or1k-core] Outdated Trap Interface Implementation](https://github.com/nanvix/hal/issues/128)
> [hal][test] Unit Tests for Trap Interface

- include/arch/core/k1b/tlb.h
- include/arch/core/or1k/tlb.h
- include/nanvix/hal/core/tlb.h
- include/nanvix/hal/core/trap.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/hooks.S
- src/hal/arch/core/or1k/mmu.c
- src/hal/arch/core/or1k/tlb.c
- src/test/syscalls.c
Description
In this Pull Request, I intruduce the enhancement proposed in the issue https://github.com/nanvix/hal/issues/170. 
- [[hal][test] Unit Tests for Trap Interface](https://github.com/nanvix/hal/pull/159)
Related Issues
- [[hal] Export TLB Types](https://github.com/nanvix/hal/issues/170)
> [hal] TLB Types

- include/arch/core/k1b/tlb.h
- include/arch/core/or1k/tlb.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/tlb.h
- include/nanvix/hal/core/trap.h
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/or1k/hooks.S
- src/hal/arch/core/or1k/mmu.c
- src/hal/arch/core/or1k/tlb.c
- src/test/syscalls.c
Description
In this Pull Request I introduce helper marcros to cast values into viartuall and physical addresses.
- [[hal] TLB Types](https://github.com/nanvix/hal/pull/171)
Related Issues
- [[hal] TLB Interface](https://github.com/nanvix/hal/issues/6)
> [hal] Casts for Virtual and Physical Address

- include/arch/core/k1b/tlb.h
- include/nanvix/hal/core/tlb.h
- src/hal/arch/core/k1b/tlb.c
Description
In this Pull Request, I introduce checks for the target TLB type in the routines of the TLB Inteface of the k1b core.
- [[k1b-core] Dont Trash In-Memory TLB](https://github.com/nanvix/hal/pull/178)
>  [k1b-core] Check for TLB Type

- include/arch/core/i486/mmu.h
- include/arch/core/k1b/mmu.h
- include/arch/core/or1k/mmu.h
- include/nanvix/hal/core/mmu.h
Related Issues
- [[hal] Kernel Page Size](https://github.com/nanvix/hal/issues/186)
> [hal] Kernel Page Size

- include/arch/core/i486/mmu.h
- include/arch/core/k1b/mmu.h
- include/arch/core/or1k/mmu.h
- include/nanvix/hal/core/mmu.h
- src/test/main.c
- src/test/test.h
- src/test/tlb.c
Description
In this Pull Request, I introduce API Tests for the TLB Interface.
Related Issues
- [[hal][test] Unit Tests for TLB Interface](https://github.com/nanvix/hal/issues/1)
- [[k1b-core] Check for TLB Type](https://github.com/nanvix/hal/pull/179)
> [hall][test] API Tests for TLB Interface

- .gitignore
- tools/dev/arch/riscv32.sh
- tools/dev/setup-qemu.sh
- tools/dev/setup-toolchain.sh
Description
- [[build] RISC-V 32bit Toolchain](https://github.com/nanvix/hal/issues/205)
> [build] RISC-V 32-bit Toolchain

- .gitignore
- build/mppa256/make/makefile
- build/optimsoc/make/makefile
- build/qemu-openrisc/make/makefile
- build/qemu-x86/make/makefile
- include/nanvix/hal/cluster.h
- include/nanvix/hal/cluster/memory.h
- include/nanvix/hal/cluster/mmio.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/cache.h
- include/nanvix/hal/core/clock.h
- include/nanvix/hal/core/context.h
- include/nanvix/hal/core/exception.h
- include/nanvix/hal/core/interrupt.h
- include/nanvix/hal/core/mmu.h
- include/nanvix/hal/core/pmio.h
- include/nanvix/hal/core/spinlock.h
- include/nanvix/hal/core/tlb.h
- include/nanvix/hal/core/trap.h
- include/nanvix/hal/core/upcall.h
- include/nanvix/hal/processor/clusters.h
- include/nanvix/hal/processor/noc.h
- include/nanvix/hal/target/stdout.h
- include/nanvix/hal/target/sync.h
- tools/dev/arch/riscv32.sh
- tools/dev/setup-qemu.sh
- tools/dev/setup-toolchain.sh
Description
With this commit, I make compile-time interface checks optional. This should make things easier when porting the HAL to new targets.
> [build] Optional Compile-Time Checks

- .gitignore
- build/mppa256/make/makefile
- build/optimsoc/make/makefile
- build/qemu-openrisc/make/makefile
- build/qemu-x86/make/makefile
- include/nanvix/hal/cluster.h
- include/nanvix/hal/cluster/memory.h
- include/nanvix/hal/cluster/mmio.h
- include/nanvix/hal/core.h
- include/nanvix/hal/core/cache.h
- include/nanvix/hal/core/clock.h
- include/nanvix/hal/core/context.h
- include/nanvix/hal/core/exception.h
- include/nanvix/hal/core/interrupt.h
- include/nanvix/hal/core/mmu.h
- include/nanvix/hal/core/pmio.h
- include/nanvix/hal/core/spinlock.h
- include/nanvix/hal/core/tlb.h
- include/nanvix/hal/core/trap.h
- include/nanvix/hal/core/upcall.h
- include/nanvix/hal/processor/clusters.h
- include/nanvix/hal/processor/noc.h
- include/nanvix/hal/target/stdout.h
- include/nanvix/hal/target/sync.h
- tools/dev/arch/riscv32.sh
- tools/dev/arch/riscv64.sh
- tools/dev/setup-pre-requisites.sh
- tools/dev/setup-qemu.sh
- tools/dev/setup-toolchain.sh
- [[build] Optional Compile-Time Checks](https://github.com/nanvix/hal/pull/210)
> [build] RISC-V 64-bit Toolchain

- include/nanvix/hal/core/interrupt.h
Related Issues
- [[hal] Simpler Hardware Interrupt Interface](https://github.com/nanvix/hal/issues/249)
> Dropping Routines from Hardware Interrupt Interface

- include/arch/core/i486/gdt.h
- include/arch/core/i486/idt.h
- include/arch/core/i486/int.h
- include/arch/core/i486/pmio.h
- include/arch/core/i486/tlb.h
- include/arch/core/i486/trap.h
- include/arch/core/i486/tss.h
- include/arch/core/or1k/regs.h
- include/arch/core/or1k/spinlock.h
- include/arch/core/or1k/trap.h
- include/arch/core/rv32i/cache.h
- include/arch/core/rv32i/int.h
- include/arch/core/rv32i/ivt.h
- include/arch/core/rv32i/pic.h
- include/arch/core/rv32i/trap.h
- include/nanvix/cc.h
- include/nanvix/const.h
- include/nanvix/klib.h
- src/hal/stdout/systrace.c
- src/test/exception.c
Description
In this Pull request, I have refactore the soruce code so as to use our C Exntesions Header (https://github.com/nanvix/hal/issues/263) instead of hard-coded GNU ones.
Related Issues
- [[hal][lib] C Compiler Extensions](https://github.com/nanvix/hal/issues/263)
- [[hal][lib] Unreachable Kernel Builtin Function](https://github.com/nanvix/hal/pull/264)
- [[hal][lib] C Compiler Extensions](https://github.com/nanvix/hal/pull/265)
> [hal][lib] Fallback to Standard Keywords

- .gdbinit
- include/arch/core/i486/gdt.h
- include/arch/core/i486/idt.h
- include/arch/core/i486/int.h
- include/arch/core/i486/pmio.h
- include/arch/core/i486/tlb.h
- include/arch/core/i486/trap.h
- include/arch/core/i486/tss.h
- include/arch/core/or1k/regs.h
- include/arch/core/or1k/spinlock.h
- include/arch/core/or1k/trap.h
- include/arch/core/rv32i/cache.h
- include/arch/core/rv32i/int.h
- include/arch/core/rv32i/ivt.h
- include/arch/core/rv32i/pic.h
- include/arch/core/rv32i/trap.h
- include/nanvix/cc.h
- include/nanvix/const.h
- include/nanvix/klib.h
- src/hal/stdout/systrace.c
- src/test/exception.c
Description
In this Pull Request, I introduce a small tweak in the GDB configuration file so that it automatically focus on the command window.
- [[hal][lib] Unreachable Kernel Builtin Function](https://github.com/nanvix/hal/pull/264)
- [[hal][lib] C Compiler Extensions](https://github.com/nanvix/hal/pull/265)
- [[hal][lib] Fallback to Standard Keywords](https://github.com/nanvix/hal/pull/266)
> [build] GDB Auto-Focus on Command Window

- src/test/core.c
Description
This PR introduces the API test "Stop Instruction Execution in a Slave Core (in Slave Core)" present in the Unit Core Tests (#2).
@ppenna It's important to note that this test is non-destructive: the key thing is make a polling in the core status and when in IDLE again, the master core sends a start signal to the previous function again, and wait for the appropriate flag in the second start. So far, at least for me, there's no need to make this test destructive. Whats your thoughts about it? If this test really need to be destructive and/or have another issues, please, let me know, =).
All the tests passed both in qemu-openrisc and OpTiMSoC.
Related Issues
- [[hal][test] Unit Tests for Core …
> [hal][test] Stop Execution in a Slave Core

- src/test/core.c
Description
This PR introduces the API test "Start Instruction Execution in a Slave Core (from Slave Core)" present in the Unit Core Tests (#2). Since this test requires at least 3 cores (master and two slaves), this test will not be compiled in archs with less than 3 cores.
All the tests passed in OpTiMSoC.
Related Issues
- [[hal][test] Unit Tests for Core Interface](https://github.com/nanvix/hal/issues/2)
----------------------------------------
- [[hal][test] Stop Execution in a Slave Core](https://github.com/nanvix/hal/pull/260)
> [hal][test] Start Execution in Slave Core from Slave

- include/arch/processor/bostan/noc/dtag.h
- src/hal/arch/processor/bostan/dtag.c
In this PR, I complete the DMA interface making small changes to start the development of Mailbox.
Related Issue: [[bostan] DMA Data Interface](#209)
> [bostan] Complete the DMA interface

- include/arch/target/kalray/mppa256.h
- include/arch/target/optimsoc/optimsoc.h
- include/arch/target/qemu/i486-pc.h
- include/arch/target/qemu/or1k-pc.h
- include/arch/target/qemu/riscv32.h
- include/nanvix/hal/target/mailbox.h
Description
In this PR, I introduce the mailbox abstraction and the routines
that comprise the interface. The abstraction is followed with a dummy
implementation to not conflict with the targets that not support the
mailbox service.
Related Issues
[[hal] Mailbox Interface](#182)
> [hal] Mailbox Interface

- build/qemu-riscv32/linker/link.ld
- include/arch/cluster/riscv32-smp/_riscv32-smp.h
- include/arch/core/rv32i/asm.h
- include/arch/core/rv32i/cache.h
- include/arch/core/rv32i/clock.h
- include/arch/core/rv32i/core.h
- include/arch/core/rv32i/excp.h
- include/arch/core/rv32i/int.h
- include/arch/core/rv32i/ivt.h
- include/arch/core/rv32i/mcall.h
- include/arch/core/rv32i/mmu.h
- include/arch/core/rv32i/pic.h
- include/arch/core/rv32i/regs.h
- include/arch/core/rv32i/spinlock.h
- include/arch/core/rv32i/trap.h
- include/arch/core/rv32i/types.h
- include/nanvix/const.h
- include/nanvix/klib.h
- src/hal/arch/core/rv32i/boot.S
- src/hal/arch/core/rv32i/clock.c
- src/hal/arch/core/rv32i/excp.c
- src/hal/arch/core/rv32i/hooks.S
- src/hal/arch/core/rv32i/int.c
- src/hal/arch/core/rv32i/ivt.c
- src/hal/arch/core/rv32i/machine.c
- src/hal/arch/core/rv32i/pic.c
- src/hal/arch/core/rv32i/setup.c
- src/hal/stdout/16550a.c
- src/test/main.c
Description
The RISC-V architecture family features a rich security scheme based on different priority levels:
- Machine Mode: grants access to bare hardware resources
- Supervisor Mode: Exposes Virtual Addressing
- User Mode: Enclaves User Applications
Even though several implementations are possible, wich feature a mix of these security modes, if we are willing to support RISC-V cores we should be able to properly deal with machine mode execution.
Related Issues
- [[rv32i] Machine Hypervisor](https://github.com/nanvix/hal/issues/259)
> [rv32i] Machine Hypervisor

- include/arch/core/rv32i/mmu.h
Description
In this commit, I introduce the implementation of the MMU Interface for rv32i cores.
Related Issues
- [[rv32i] MMU Interface](https://github.com/nanvix/hal/issues/218)
------------------------------------------
- [[rv32i] Machine Hypervisor](https://github.com/nanvix/hal/pull/274)
> [rv32i] MMU Interface

- include/arch/core/rv32i.h
- include/arch/core/rv32i/tlb.h
Description
In this commit, I introduce the implementation of the TLB Interface for rv32i cores.
Related Issues
- [[rv32i] TLB Interface](https://github.com/nanvix/hal/issues/219)
------------------------------------------
- [[rv32i] Machine Hypervisor](https://github.com/nanvix/hal/pull/274)
- [[rv32i] MMU Interface](https://github.com/nanvix/hal/pull/282)
> [rv32i] TLB Interface

- src/test/core.c
Description
This PR introduces the API test "Suspend and Resume Instruction Execution (from Slave Core)" present in the Unit Core Tests (#2). Since this test requires at least 3 cores (master and two slaves), this test will not be compiled in archs with less than 3 cores.
All the tests passed in OpTiMSoC.
Related Issues
- [[hal][test] Unit Tests for Core Interface](https://github.com/nanvix/hal/issues/2)
> [hal][test] Enhancement: Suspend and Resume from Slave

- include/nanvix/cc.h
Description
In this pull request, I have replaced the previous `EXPECT()` builtin functions with two other builtins:
- `LIKELY()`: hints a condition that is likely to hold
- `UNLIKELY()` hints a condition that is unlikely to hold
> [hal][lib] Builtins Likely and Unlikely

- src/hal/arch/core/or1k/clock.c
Description
Since the timer counter is reprogrammed at every timer interrupt, the counter can be sensible to the own timer handling. In order to ease this scenario and choose an appropriate timer value, the calibrate routine is introduced, that calculates the minimal time spent between two consecutive reads.
This way, the counter can be programmed in a more predictable way.
Related Issues
[[or1k] Calibrate Timer of Clock Device](https://github.com/nanvix/hal/issues/250)
> [or1k-core] Calibrate the Timer of Clock Device

- include/arch/core/i486/context.h
- include/arch/core/i486/excp.h
- include/arch/core/i486/idt.h
- include/arch/core/k1b/context.h
- include/arch/core/k1b/excp.h
- include/arch/core/k1b/ivt.h
- include/arch/core/or1k/context.h
- include/arch/core/or1k/excp.h
- include/arch/core/rv32i/context.h
- include/arch/core/rv32i/excp.h
- include/arch/core/rv32i/ivt.h
- include/nanvix/hal/core/exception.h
- src/hal/arch/cluster/or1k-cluster/memory.c
- src/hal/arch/core/i486/ctx.c
- src/hal/arch/core/i486/hooks.S
- src/hal/arch/core/i486/idt.c
- src/hal/arch/core/k1b/excp.c
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/ivt.c
- src/hal/arch/core/or1k/ctx.c
- src/hal/arch/core/or1k/hooks.S
- src/hal/arch/core/rv32i/ctx.c
- src/hal/arch/core/rv32i/hooks.S
- src/hal/arch/core/rv32i/machine.c
- src/hal/core/exception.c
- src/test/exception.c
Description
In this Pull Request, I introduce a refactor in the Exception Interface so as most of exception handling code becomes platform-independent.
Related Issue
- [[hal] Exception Interface](https://github.com/nanvix/hal/issues/9)
> Platform-Independent Exception Interface

- include/arch/core/i486/asm.h
- include/arch/core/i486/ctx.h
- include/arch/core/i486/excp.h
- include/arch/core/k1b/asm.h
- include/arch/core/k1b/ctx.h
- include/arch/core/k1b/excp.h
- include/arch/core/k1b/int.h
- include/arch/core/or1k/asm.h
- include/arch/core/or1k/context.h
- include/arch/core/or1k/ctx.h
- include/arch/core/or1k/excp.h
- include/arch/core/rv32i/asm.h
- include/arch/core/rv32i/ctx.h
- include/arch/core/rv32i/excp.h
- include/arch/core/rv32i/int.h
- include/arch/core/rv32i/machine.h
- src/hal/arch/core/i486/_upcall.S
- src/hal/arch/core/i486/ctx.c
- src/hal/arch/core/i486/hooks.S
- src/hal/arch/core/k1b/_upcall.S
- src/hal/arch/core/k1b/ctx.c
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/int.c
- src/hal/arch/core/k1b/ivt.c
- src/hal/arch/core/or1k/_upcall.S
- src/hal/arch/core/or1k/ctx.c
- src/hal/arch/core/rv32i/ctx.c
- src/hal/arch/core/rv32i/machine.c
Description
In this Pull Request I have renamed the headers of the context interface so that they are the same in all targets.
> Renaming Context Interface Headers

- include/arch/core/i486.h
- include/arch/core/i486/tlb.h
- include/arch/core/k1b.h
- include/arch/core/k1b/tlb.h
- include/arch/core/mor1kx.h
- include/arch/core/or1k.h
- include/arch/core/or1k/tlb.h
- include/arch/core/rv32i.h
- include/arch/core/rv32i/tlb.h
- include/nanvix/hal/core/exception.h
- include/nanvix/hal/core/pmio.h
- include/nanvix/hal/core/tlb.h
- src/test/tlb.c
Description
In this Pull Request I have reworked the features list of all supported cores.
> [hal] Core Features

- include/arch/cluster/k1b-cluster/clock.h
- include/arch/cluster/or1k-cluster/clock.h
- include/arch/cluster/riscv32-cluster/clock.h
- include/arch/core/k1b/clock.h
- include/arch/core/mor1kx/clock.h
- include/arch/core/or1k/clock.h
- include/arch/core/rv32gc/clock.h
- include/nanvix/hal/cluster.h
- include/nanvix/hal/cluster/clock.h
- include/nanvix/hal/core.h
- src/hal/arch/core/k1b/clock.c
- src/hal/arch/core/or1k/clock.c
- src/hal/arch/core/or1k/int.c
- src/hal/arch/core/rv32gc/clock.c
- src/hal/core/interrupt.c
Description
In this Pull Request, I refactor the Clock Interface. In summary, I moved the implementation of this interface to the Cluster AL.
Related Issues
- [[hal] Move Clock Interface to Cluster AL](https://github.com/nanvix/hal/issues/294)
> [hal] Refactoring Clock Interface

- include/arch/core/rv32gc/upcall.h
- src/hal/arch/core/rv32gc/_upcall.S
- src/hal/arch/core/rv32gc/hooks.S
- src/test/build/makefile.qemu-riscv32
- src/test/core/arch/rv32gc.S
- src/test/main.c
Description
In this Pull Request, I introduce the Upcall Interface for rv32gc core family.
Related Issues
- [[rv32gc] Upcall Interface](https://github.com/nanvix/hal/issues/228)
> [rv32gc] Upcall Interface

- include/arch/core/i486/mmu.h
- include/arch/core/i486/types.h
- src/hal/arch/core/i486/mmu.c
Description
In this PR I introduce MMU extensions for i486 cores.
- [[i486] Extensions for MMU Interface](https://github.com/nanvix/hal/issues/367)
> [i486] MMU Extensions

- include/arch/core/i486.h
- include/arch/core/i486/mmu.h
- include/arch/core/k1b.h
- include/arch/core/k1b/mmu.h
- include/arch/core/mor1kx.h
- include/arch/core/or1k.h
- include/arch/core/or1k/mmu.h
- include/arch/core/rv32gc.h
- include/arch/core/rv32gc/mmu.h
- include/nanvix/hal/core/mmu.h
Description
We were missing some operations of the MMU Interface. In this Pull Request I fix this bug.
Related Issues
- [[hal] Missing MMU Operations](https://github.com/nanvix/hal/issues/381)
> [hal] Missing MMU Operations

- include/nanvix/hal/cluster.h
- src/hal/arch/cluster/k1b-cluster/cluster.c
- src/hal/arch/cluster/or1k-cluster/cluster.c
- src/hal/arch/cluster/riscv32-cluster/machine.c
- src/hal/cluster/cluster.c
Description
In this PR, I move the implementation of Startup Fence to Cluster AL.
Related Issues
- [[hal] Platform Independent Startup Fence](https://github.com/nanvix/hal/pull/409)
> [hal] Platform Independent Startup Fence

- include/arch/cluster/optimsoc-cluster/ompic.h
- include/arch/core/mor1kx.h
- include/arch/core/mor1kx/perf.h
- include/arch/core/or1k/regs.h
- src/hal/arch/core/mor1kx/perf.c
- src/hal/build/makefile.optimsoc
Description
This PR introduces support for Performance Counters for the optimsoc (mor1kx-core) target.
Related Issues
- [[or1k-core] Performance Monitoring Interface](https://github.com/nanvix/hal/issues/405)
> [mor1kx-core] Performance Monitoring Interface

- build/unix64/make/makefile
- include/arch/cluster/linux64-cluster.h
- include/arch/cluster/linux64-cluster/_linux64-cluster.h
- include/arch/core/linux64.h
- include/arch/core/linux64/cache.h
- include/arch/core/linux64/core.h
- include/arch/core/linux64/excp.h
- include/arch/core/linux64/int.h
- include/arch/core/linux64/spinlock.h
- include/arch/core/linux64/types.h
- include/arch/processor/linux64.h
- include/arch/processor/linux64/_linux64.h
- include/arch/stdout/tty-virt.h
- include/arch/target/unix64/unix64.h
- include/arch/target/unix64/unix64/_unix64.h
- include/arch/target/unix64/unix64/stdout.h
- include/nanvix/hal/cluster.h
- include/nanvix/hal/cluster/_cluster.h
- include/nanvix/hal/core/_core.h
- include/nanvix/hal/processor/_processor.h
- include/nanvix/hal/target/_target.h
- src/build/processor/makefile.linux64
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/arch/cluster/linux64-cluster/cluster.c
- src/hal/arch/core/linux64-core/core.c
- src/hal/build/makefile.unix64
- src/hal/stdout/tty-virt.c
- src/test/build/makefile.unix64
- src/test/main.c
Description
In this PR we introduce the Core Interface for the Linux 64-bit Virtual Core.
Related Issues
- [[linux64-core] Core Interface](https://github.com/nanvix/hal/issues/433)
> [linux64-core] Core Interface

- .travis.yml
- build/unix64/make/makefile.cflags
Description
This is the PR for the Addition of the builds in TravisCI for the UNIX 64-bit target.
Related Issues
- [[test] TravisCI Build Support for UNIX 64-bit](https://github.com/nanvix/hal/issues/431)
> [test] TravisCI Build Support for UNIX 64-bit

- include/arch/cluster/linux64-cluster/timer.h
- src/hal/arch/core/linux64-core/timer.c
- src/test/build/makefile.unix64
- src/test/cluster/timer.c
- src/test/main.c
- src/test/test.h
Description
This is the PR about the Timer interface
Related Issues
- [[linux64-core] Clock Interface](https://github.com/nanvix/hal/issues/467)
> [linux64-core] Timer Interface

- include/arch/cluster/linux64-cluster/_linux64-cluster.h
- include/arch/cluster/linux64-cluster/cores.h
- include/arch/core/linux64/core.h
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/arch/cluster/linux64-cluster/cores.c
- src/hal/arch/cluster/linux64-cluster/memory.c
This is the PR about the move of the core functions into the cluster
> [linux64-cluster] Moving Cores Interface

- src/test/cluster/cores.c
Description
In order to make sure that the spinlocks implementation works as expected, the classic producer/consumer was implemented as a stress test, thus, ensuring that the current spinlocks implementation works as expected.
> [hal] Enhancement: Producer and Consumer Stress Test

- src/hal/klib/kvsprintf.c
This is the PR about the enhancement of the kprintf function
> [lib] 64 Bit Formatted Printing

- build/unix64/make/makefile
- include/arch/core/linux64.h
- include/arch/core/linux64/trap.h
- include/nanvix/hal/core/trap.h
- src/test/build/makefile.unix64
- src/test/core/syscalls.c
- src/test/main.c
Description
This is the PR about the Trap Interface on linux64
Related Issues
- [[linux64-core] Trap Interface](https://github.com/nanvix/hal/issues/464)
> Feature unix64 traps

- include/arch/core/linux64/ctx.h
- include/nanvix/hal/core/context.h
- src/hal/arch/core/linux64-core/ctx.c
Description
This is the PR about the context interface for linux64
Related Issues
- [[linux64-core] Execution Context Interface](https://github.com/nanvix/hal/issues/466)
> [linux64-core] Execution Context Interface

- include/arch/core/linux64/excp.h
- include/nanvix/hal/core/exception.h
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/arch/cluster/linux64-cluster/cores.c
- src/hal/arch/core/linux64-core/ctx.c
- src/hal/arch/core/linux64-core/excp.c
- src/hal/build/makefile.unix64
- src/test/build/makefile.unix64
- src/test/core/exception.c
- src/test/main.c
Description
This is the PR about the exception interface.
Related Issues
- [[linux64-core] Exception Interface](https://github.com/nanvix/hal/issues/463)
> [linux64-core] Exception Interface

- include/arch/core/linux64/int.h
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/arch/core/linux64-core/int.c
- src/hal/build/makefile.unix64
- src/test/build/makefile.unix64
- src/test/core/interrupt.c
- src/test/main.c
Description
This is the PR about the interrupt Interface
Related Issues
- [[linux64-core] Hardware Interrupt Interface](https://github.com/nanvix/hal/issues/465)
> [linux64-core] Hardware Interrupt Interface

- include/arch/core/linux64.h
- include/arch/core/linux64/perf.h
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/build/makefile.unix64
- src/test/build/makefile.unix64
- src/test/main.c
Description
This is the PR avout the perf interface for linux64
Related Issues
- [[linux64-core] Performance Monitoring Interface ](https://github.com/nanvix/hal/issues/468)
> [linux64-core] Performance Monitoring Interface 

- include/arch/core/linux64/upcall.h
Description
This is the PR about the Dummy Upcall Interface for linux64
Related Issues
- [[linux64-core] Upcall Interface](https://github.com/nanvix/hal/issues/470)
> [linux64-core] Upcall Interface

- src/hal/arch/core/linux64-core/cache.c
- src/hal/arch/core/linux64-core/math.c
This is the PR about the enhancement of the cache interface..Now every core has it's own configuration and counters.
> [linux64-core] Cache Interface

- src/hal/arch/cluster/linux64-cluster/memory.c
This is the PR about the enhancement of the counter in the TLB interface of the linux64-cluster
> [linux64-cluster] TLB Interface

- include/arch/cluster/linux64-cluster.h
- include/arch/cluster/linux64-cluster/_linux64-cluster.h
- include/arch/cluster/linux64-cluster/cores.h
- include/arch/cluster/linux64-cluster/event.h
- include/arch/core/linux64/spinlock.h
- src/hal/arch/cluster/linux64-cluster/boot.c
- src/hal/arch/cluster/linux64-cluster/cluster.c
- src/hal/arch/cluster/linux64-cluster/cores.c
- src/hal/arch/cluster/linux64-cluster/event.c
- src/hal/arch/cluster/riscv32-cluster/cluster.c
- src/hal/build/makefile.unix64
This is the PR about the cluster interface for linux64
> [linux64-cluster] Cluster Interface

- .travis.yml
- build/makefile.run
- build/mppa256/make/makefile
- build/optimsoc/make/makefile
- build/qemu-openrisc/make/makefile
- build/qemu-riscv32/make/makefile
- build/qemu-x86/make/makefile
- build/unix64/make/makefile
- src/test/main.c
This is the PR about the automated tests for unix64 and openrisc within TravisCI
- [[Build] Unit Tests in TravisCI](https://github.com/nanvix/hal/issues/508)
> [Build] Automated tests with TravisCI

- include/arch/processor/bostan/noc/ctag.h
- include/arch/processor/bostan/noc/dma.h
- include/arch/processor/bostan/noc/dtag.h
- src/hal/arch/processor/bostan/ctag.c
- src/hal/arch/processor/bostan/dma.c
- src/hal/arch/processor/bostan/dtag.c
- src/test/main.c
- src/test/processor/cnoc.c
- src/test/processor/dnoc.c
- src/test/test.h
Description
This PR introduces Data NoC implementation and tests in order to proceed with the Mailbox and Portal Interfaces development for MPPA-256.
Related Issues
- [[bostan] DMA Data Interface](https://github.com/nanvix/hal/issues/209)
> [bostan-processor] DMA Data Interface

- include/arch/processor/bostan.h
- include/arch/processor/bostan/noc/ctag.h
- include/arch/processor/bostan/noc/dtag.h
- include/arch/target/kalray/mppa256.h
- include/arch/target/kalray/mppa256/mailbox.h
- include/arch/target/kalray/mppa256/portal.h
- include/arch/target/kalray/mppa256/sync.h
- include/nanvix/hal/target.h
- include/nanvix/hal/target/_target.h
- include/nanvix/hal/target/mailbox.h
- include/nanvix/hal/target/portal.h
- include/nanvix/hal/target/sync.h
- src/hal/arch/target/mppa256/mailbox.c
- src/hal/arch/target/mppa256/portal.c
- src/hal/arch/target/mppa256/sync.c
- src/test/main.c
- src/test/target/mailbox.c
- src/test/target/sync.c
In this PR, I separated the changes into 3 major commits. The main reason for this PR is the changes to the interfaces that need to be made. The items below exemplify what each commit contains.
- Sync: Contains changes to sync_open calls and any changes to the source files.
- Mailbox: Contains the first functional version of abstraction for the MPPA-256 processor.
- Portal: Contains a first untested version for the MPPA-256 processor.
> [hal] Sync, Mailbox and Portal Interfaces

- include/nanvix/hal/core/exception.h
- src/hal/arch/core/linux64-core/excp.c
- src/hal/core/exception.c
- src/hal/hal.c
- [[hal] Platform Independent Exception Setup](https://github.com/nanvix/hal/issues/455)
> Generic Exception Setup

- src/test/target/sync.c
In this PR, I add the bad create/open synchronization points unit tests.
Related Issues
- [[hal][test] Unit Tests for Sync Interface](https://github.com/nanvix/hal/issues/98)
> [hal] Unit tests for Sync Interface

- src/hal/arch/processor/bostan/ctag.c
- src/hal/arch/processor/bostan/dtag.c
In this PR, I mask NoC interrupt on its handlers. After cleaning the hardware flags, I unmask the interrupt and go to the user handler.
> [k1b] Bug fix: No masking interrupts in NoC handler.

- src/hal/arch/target/mppa256/portal.c
In this commit, I allow a read permission where previously only a `portal_allow` call by` portal_create` was allowed.
> [mppa256] Bad Behavior of Portal Allow

- include/nanvix/hal/processor/noc.h
- src/hal/arch/target/mppa256/mailbox.c
- src/hal/arch/target/mppa256/portal.c
- src/hal/arch/target/unix64/mailbox.c
- src/hal/arch/target/unix64/portal.c
- src/hal/target/mailbox.c
- src/hal/target/portal.c
In this PR I introduce two function to check if a given node is local and valid.
> [target] Cleanup of Mailbox and Portal Interfaces

- img/unix64.img
- src/test/main.c
- src/test/makefile
- src/test/stress/barrier.c
- src/test/stress/barrier.h
- src/test/stress/combination.c
- src/test/stress/mailbox.c
- src/test/stress/portal.c
- src/test/target/mailbox.c
- src/test/target/portal.c
- src/test/target/sync.c
- src/test/test.h
In this PR, I introduce stress tests for IKC interfaces.
> [test] IKC Stress Sests

- img/unix64.img
- src/test/main.c
- src/test/makefile
- src/test/stress/barrier.c
- src/test/stress/barrier.h
- src/test/stress/combination.c
- src/test/stress/mailbox.c
- src/test/stress/portal.c
- src/test/target/mailbox.c
- src/test/target/portal.c
- src/test/target/sync.c
- src/test/test.h
In this PR, I introduce stress tests of mailbox, portal and a combination of mailbox and portal.
> [test] Stress Tests for Communication Abstractions

- src/hal/arch/target/unix64/portal.c
In this PR, the Portal Read / Write now return errors when a communication operation doesn't met the requirements to occur at the specified moment, instead of blocking until they are reached.
This is an attempt of solving the Unix Microkernel freezing problem. Need more tests to ensure it.
> [unix64] Portal Non-Blocking Read/Write

- build/unix64/make/makefile.cflags
In this PR, I select CFLAGS manually because -O3 is breaking the execution on Unix.
> [unix] Bugfix: Insecure optimizations

- include/arch/target/kalray/mppa256/mailbox.h
- include/arch/target/unix64/unix64/mailbox.h
In this PR, I increase the mailbox size to 128 to support the header in the mailbox.
> [target] Enhancement: Increases the mailbox size

- include/nanvix/hal/resource.h
In this PR I add support for the following flags in the resource abstraction:
- Valid: asserts if a resource is valid
- Dirty: asserts if a data resource is not synced with underlying backup memory
> [hal] Extensions for Resource Abstraction

- src/hal/arch/target/unix64/sync.c
In this PR, I introduce counters to the sync table to keep the number of signals a sync point received from a cluster. This avoids dropping signals. 
[[unix64] Unnecessary dropping of signals in the Sync module #591](https://github.com/nanvix/hal/issues/591)
> [unix64] Don't Drop Signals in the Sync Module

- src/hal/arch/target/mppa256/sync.c
In this PR, I change the hash structure to be more stable. Now, we use primitive types instead of bit-fields.
Bug fixed: When using bit-fields, there is the possibility of introducing an undefined behavior. For instance, the kernel prints do not present correct field values.
> [mppa256] Change Hash Structure to Use Primitive Types

- include/arch/core/k1b/asm.h
- include/arch/core/k1b/ctx.h
- include/arch/core/k1b/int.h
- src/hal/arch/cluster/k1b-cluster/_cluster.S
- src/hal/arch/core/k1b/_upcall.S
- src/hal/arch/core/k1b/ctx.c
- src/hal/arch/core/k1b/hooks.S
- src/hal/arch/core/k1b/ivt.c
In this PR, I add virtual registers that are saved by mOS but we are not saving. I also correctly save/restore a context.
Closes #614
> [k1b-core] Add virtual Registers and Correctly Restore the Context 

- src/test/stress/api.c
- src/test/stress/barrier.c
- src/test/stress/combination.c
- src/test/stress/mailbox.c
- src/test/stress/portal.c
- src/test/stress/stress.h
- src/test/stress/vsyscall.c
- src/test/stress/vsyscall.h
In this PR, I create a virtual syscall system to move the responsibility to do the comm operations to the master core.
> [test] Enhancement: Master core do comm operations and slave waits for it

- src/test/core/arithmetic.c
- src/test/main.c
- src/test/makefile
- src/test/test.h
In this PR, I add tests to perform 32-bit integer (and less of 32-bit) operations.
64-bit integer operations still not supported.
> [test] 32-bit Integer Arithmetic Tests

- include/arch/core/k1b/spinlock.h
In this PR, I insert a silly job in the lock to minimize competition and the
the starvation problem in the spinlock.
Mentions #625
> [k1b-core] Mitigate Starvation on Spinlocks

- include/arch/cluster/k1b-cluster/memory.h
> [BugFix] Increased Kernel Pool Size

- include/nanvix/hal/resource.h
- src/hal/resource.c
- src/test/abstract/resource.c
- src/test/main.c
- src/test/makefile
- src/test/test.h
In this PR, I abstract the resource queues and lists into generic arrangements of resources. In that way, we can facilitate the use of these structures where the function that manipulates the structures defines how to sees them.
The following PR must be accepted before the review of this PR:
- Mentions #637
> [hal] Increase the Abstraction of Resource Arrangements

- src/hal/resource.c
In this PR, we add a Spinlock to guarantee thread-safeness when allocating and freeing a resource from a resource pool. This enhancement was introduced to avoid data race conditions in scenarios where multiple threads compete for a specific resource allocation.
> [resource] Thread-safe Resource

- src/hal/arch/core/rv32gc/machine.c
> [rv32gc] Bug Fix: SUM Bit not Being Set
